Задачи по NumPy

In [1]:
import numpy as np

In [ ]:
# Задача № 1 
# Выход: Создайте одномерный массив из 5 целых чисел от 0 до 4

# ваш код


In [ ]:
# Задача № 2
# Выход: Создайте двумерный массив размером 4x5, заполненный нулями

# ваш код


In [ ]:
# Задача № 3
# Выход: Создайте массив размером 3x2, заполненный единицами

# ваш код


In [ ]:
# Задача № 4
# Выход: Создайте одномерный массив из четных чисел от 0 до 8 (включительно) с шагом 2

# ваш код


In [ ]:
# Задача № 5
# Выход: Создайте массив из 5 равномерно распределенных значений между 0 и 1, включая обе границы

# ваш код


In [ ]:
# Задача № 6
# Выход: Создайте массив размером 2x3, заполненного значением 7

# ваш код


In [ ]:
# Задача № 7
# Выход: Создайте массив из 5 строк и 2 столбцов, содержащий только булевы значения True

# ваш код


In [ ]:
# Задача № 8
# Выход: Создайте трехмерный массив (каждый массив должен содержать две строки и четыре столбца) и определите его количество измерений

# ваш код


In [ ]:
# Задача № 9
# Выход: Создайте матрицу 3x4 заполненную единицами и определите её размеры

# ваш код


In [ ]:
# Задача № 10
# Выход: Создайте квадратную матрицу 4x4 с единицами на главной диагонали

# ваш код


In [ ]:
# Задача № 11
# Выход: Повторите созданный массив с элементами (1, 2, 3) 3 раза, чтобы получить в итоге такой массив

# ваш код


In [ ]:
# Задача № 12
# Выход: Повторите созданный массив с элементами (1, 2, 3) 4 раза вдоль оси 0 (строки)
# и дополнительно, каждую строку массива увеличьте по размеру в два раза с те же элементами (вдоль оси 1(столбцы))

# ваш код


In [ ]:
# Задача № 13
# Выход: Повторите созданный массив с элементами (1, 2, 3) 4 раза вдоль оси 0 (строки)
# и дополнительно, каждую строку массива увеличьте по размеру в два раза с те же
# элементами (вдоль оси 1 (столбцы)), и еще, дополнительно, сделайте этот массив двумерным

# ваш код


In [ ]:
# Задача № 14
# Дано: У вас есть массив arr с целыми числами.
# Выход: Напишите программу для определения текущего типа данных элементов массива

arr = np.array([1, 2, 3, 4])

# ваш код


In [ ]:
# Задача № 15
# Выход: создать массив arr с числами от 1 до 3, включительно, и указать явно тип данных целых чисел

# ваш код


In [ ]:
# Задача № 16
# Дано: массив arr_float с вещественными числами 
# Выход: напишите программу для создания нового массива arr_int, в котором вещественные числа будут округлены до целых

arr_float = np.array([1.2, 2.5, 3.8, 4.1])

# ваш код


In [ ]:
# Задача № 17
# Дано: два датасета с данными о температуре и влажности. Каждый датасет представлен в виде двумерного массива,
# где строки представляют дни, а столбцы представляют конкретные моменты времени в течение дня. Тип данных - int. Вам нужно изменить их на float.
# Выход: 1. Создайте функцию, которая принимает на вход два аргумента: dataset и new_dtype.
#        2. Используйте функцию для изменения типа данных каждого датасета на тип float.

# Датасет температуры (тип данных: int)
temp_data = np.array([[22, 25, 24, 23, 21],
                      [20, 18, 19, 22, 24]])

# Датасет влажности (тип данных: int)
humid_data = np.array([[45, 50, 48, 52, 47],
                       [45, 48, 50, 51, 53]])

# ваш код


In [ ]:
# Задача № 18
# Выход: Выполните поэлементное сложение двух массивов arr1 и arr2 и выведите результат на экран

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[3, 2, 1]])

# ваш код


In [ ]:
# Задача № 19
# Выход: Выполните поэлементное умножение двух массивов arr1 и arr2 и выведите результат на экран

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

# ваш код


In [ ]:
# Задача № 20
# Выход: Выполните поэлементное деление массива на 2 и сохраните результат в result_divide

arr1 = np.array([[8, 8, 4], 
                 [4, 2, 2], 
                 [10, 10, 2]])

# ваш код


In [ ]:
# Задача № 21
# Выход: Выполните поэлементное сложение двух массивов и сохраните результат в массив result_add

arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])

arr2 = np.array([[9, 8, 7], 
                 [6, 5, 4], 
                 [3, 2, 1]])

# ваш код


In [ ]:
# Задача № 22
# Выход: Выполните поэлементное вычитание arr1 из arr2 и сохраните результат в массив result_subtract

arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])

arr2 = np.array([[10, 11, 12], 
                 [13, 14, 15], 
                 [16, 17, 18]])

# ваш код


In [ ]:
# Задача № 23
# Выход: Возведите все элементы массива в квадрат и сохраните результат в result_double

arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])

# ваш код


In [ ]:
# Задача № 24
# Дано: массив grades из оценок студентов (от 0 до 100).
# Выход: Преобразуйте тип данных массива grades на float, затем напишите код, который увеличит все оценки более 50 на 10%

grades = np.array([75, 45, 60, 90, 30, 85, 40])

# ваш код


In [ ]:
# Задача № 25
# Выход: Выполните умножение вектора (vector) на скаляр (scalar)

vector = np.array([1, 2, 3, 4])
scalar = 2

# ваш код


In [ ]:
# Задача № 26
# Дано: массив prices из цен на товары
# Выход: напишите код, который уменьшит цены на 10% для товаров с ценой выше 40

prices = np.array([50, 30, 70, 40, 90], float)

# ваш код


In [ ]:
# Задача № 27
# Выход: выполните сложение матрицы и вектора

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

vector = np.array([0, 1, 2])

# ваш код


In [ ]:
# Задача № 28
# Выход: выполните умножение матриц matrix_a и matrix_b. Создайте matrix_b с такими значениями, чтобы получить в итоге умножения такую матрицу:
# [[ 10  20  30]
# [ 80 100 120]
# [210 240 270]]

matrix_a = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])

# ваш код


In [ ]:
# Задача № 29
# Выход: выполните вычитание матриц matrix_c и matrix_d. Создайте matrix_d с такими значениями, чтобы получить в итоге вычитания такую матрицу:
# [[ 9 18 27]
# [39 48 57]
# [69 78 87]]

matrix_c = np.array([[10, 20, 30], 
                     [40, 50, 60], 
                     [70, 80, 90]])

# ваш код


In [ ]:
# Задача № 30
# Выход: выполните умножение матриц matrix_e и matrix_f. Создайте matrix_f с такими значениями, чтобы получить в итоге умножения такую матрицу:
# [[ 2 8]
# [18 32]]

matrix_e = np.array([[2, 4], 
                     [6, 8]])

# ваш код


In [ ]:
# Задача № 31
# Выход: выведите первый и последний элементы с помощью срезов

arr = np.array([1, 2, 3, 4, 5])

# ваш код


In [ ]:
# Задача № 32
# Выход: выведите вторую строку и третий столбец с помощью срезов

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

# ваш код


In [ ]:
# Задача № 33
# Выход: выведите первый слой, вторую строку и первый столбец с помощью срезов

arr = np.array([[[1, 2], 
                 [3, 4]], 
                [[5, 6], 
                 [7, 8]], 
                [[9, 10], 
                 [11, 12]]])

# ваш код


In [ ]:
# Задача № 34
# Выход: выведите все элементы в четных столбцах

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# ваш код


In [ ]:
# Задача № 35
# Выход: выведите все элементы в нечетных столбцах

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# ваш код


In [ ]:
# Задача № 36
# Выход: выведите все элементы с нечетными строками

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# ваш код


In [ ]:
# Задача № 37
# Выход: выделите подматрицу, состоящую из трех последних строк и двух первых столбцов

matrix = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25]])

# ваш код


In [ ]:
# Задача № 38
# Выход: выделите подматрицу, состоящую из второй и третьей строк, а также третьего и четвёртого столбцов

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

# ваш код


In [ ]:
# Задача № 39
# Выход: выведите подматрицу, состоящую из элементов с индексами от 1 до 2 по обеим осям, с помощью срезов

arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12], 
                [13, 14, 15, 16]])

# ваш код


In [ ]:
# Задача № 40
# Выход: выведите элементы в обратном порядке с шагом 2 с помощью срезов

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# ваш код


In [ ]:
# Задача № 41
# Выход: выберите подматрицу 2x2 в верхнем левом углу для каждой матрицы

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код


In [ ]:
# Задача № 42
# Выход: выберите второй столбец для каждой строки в каждой матрице

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код


In [ ]:
# Задача № 43
# Выход: выберите все элементы второй строки для каждой матрицы

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код


In [ ]:
# Задача № 44
# Выход: выберите элементы в каждой матрице в нижнем правом углу, начиная с третьей строки
# и третьего столбца и до конца каждой матрицы. Обратите внимание - результат должен быть 
# трехмерным массивом, где каждая подматрица содержит элементы в нижнем правом углу соответствующей матрицы

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код


In [ ]:
# Задача № 45
# Выход: выберите четные строки и четные столбцы в каждой матрице

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]], 

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код
