Варианты решения задач

In [1]:
import numpy as np

In [ ]:
# Задача № 1 
# Дано два целых числа
# Выход: массив NumPy из этих чисел

a = 3
b = 2

# ваш код

arr = np.array((a, b))
print(arr)

[3 2]


In [ ]:
# Задача № 2 
# Дано 3 вещественных числа
# Выход: массив NumPy из этих чисел

a = 3.3
b = 3
c = 2.2

# ваш код

arr = np.array((a, b, c))
print(arr)

[3.3 3.  2.2]


In [ ]:
# Задача № 3
# Дано двенадцать чисел: координаты точек начала и конца первого вектора x1, y1, z1, x2, y2, z2 и
# координаты точек начала и конца второго вектора x3, y3, z3, x4, y4, z4
# Выход: True, если вектора равны, иначе False.

x1, y1, z1, x2, y2, z2 = 1, 2, 3, 3, 4, 5
x3, y3, z3, x4, y4, z4 = -3, 3, 2, -1, 5, 4

# ваш код

a = np.array([x2-x1, y2-y1, z2-z1])
b = np.array([x4-x3, y4-y3, z4-z3])
print(not False in (a == b))

True


In [ ]:
# Задача № 4
# Дано натуральное число и вектор с координатами [0.5, 0.25, 0.125, ..., 0.5^n]
# Выход: L1 норма вектора

n = 4

# ваш код

v = np.array([0.5**i for i in range(1, n+1)])
print(np.linalg.norm(v, ord=1))


0.9375


In [ ]:
# Задача № 5
# Дано координаты векторов
# Выход: Сумма векторов

a = np.array((1, 2, 1))
b = np.array((-1, 2, 0))

# ваш код

print(a+b)

[0 4 1]


In [ ]:
# Задача № 6
# Дано восемь чисел: координаты точек начала и конца первого вектора x1, y1, x2, y2 и
# координаты точек начала и конца второго вектора x3, y3, x4, y4
# Выход: модуль вектора суммы векторов

x1, y1, x2, y2 = 0, 0, 0, 0
x3, y3, x4, y4 = 0, 0, 0, 5

# ваш код

a = np.array([x2-x1, y2-y1])
b = np.array([x4-x3, y4-y3])
print(np.linalg.norm(a+b))

5.0


In [ ]:
# Задача № 7
# Дано два вектора
# Выход: модуль разности векторов

a = np.array((2, 3, 2))
b = np.array((1, 3, 2))

# ваш код

c = a-b
print(np.linalg.norm(c))

1.0


In [3]:
# Задача № 8
# Дано координаты точек A, B, D параллелограмма ABCD
# Выход: длины диагоналей AC, BD

A = np.array([0, 0])
B = np.array([0, 4])
D = np.array([3, 0])

# ваш код

BD = np.linalg.norm(B-D)
AD = np.linalg.norm(A-D)
AB = np.linalg.norm(A-B)
AC = (2*(AD**2 + AB**2) - BD**2)**0.5
print(AC, BD)

5.0 5.0


In [4]:
# Задача № 9
# Дано координаты сил, действующих на материальную точку
# Выход: модуль равнодействующей сил

a = np.array([2, 0, 0])
b = np.array([-2, 0, 0])

# ваш код

print(np.linalg.norm(a+b))


0.0


In [ ]:
# Задача № 10
# Дано координаты двух векторов a и b
# Выход: модуль вектора, полученного вычитанием вектора b умноженного на два из вектора a умноженного на три

a = np.array([0, 0, 0])
b = np.array([0, 2, 0])

# ваш код

c = 3*a - 2*b
print(np.linalg.norm(c))

4.0


In [10]:
# Задача № 11
# Дано координаты двух векторов a и b
# Выход: True, если вектора коллиенарны, False в противном случае

a = np.array([1, 2, 3])
b = np.array([2, 4, 6])

# ваш код

print(np.all(np.cross(a, b) == 0))

True


In [15]:
# Задача № 12
# Дано координаты точек A, B, целое число k
# Выход: координаты точки С, которая делит отрезок АВ в отношении k

A = np.array([1, -2, 3])
B = np.array([0, 3, 2])
k = 5

# ваш код

C = np.round((A+k*B)/(k+1), 2)
print(C)

[0.17 2.17 2.17]


In [16]:
# Задача № 13
# Дано координаты вектора в некотором базисе
# Выход: косинусы углов между этим вектором и осями координат ox, oy, oz

a = np.array([-1, 3, 2])

# ваш код

norm = np.linalg.norm(a) 
print(round(a[0]/norm, 2), round(a[1]/norm, 2), round(a[2]/norm, 2))

-0.27 0.8 0.53


In [19]:
# Задача № 14
# Дано модуль вектора, лежащего на плоскости и угол в радианах между осью ох и вектором
# Выход: проекции вектора на оси ох и оу

m = 2.3
angle_rad = 1.57

# ваш код

print(round(np.cos(angle_rad)*m, 2), round(np.sin(angle_rad)*m, 2))

0.0 2.3


In [ ]:
# Задача № 15
# Дано координаты векторов a и b
# Выход: модуль вектора a, модуль вектора c1 = (a+b), модуль вектора (с4+с3), 
# где вектор c3 в два раза длиннее вектора a и противоположен ему,
# вектор c4 - направлен в том же направлении, что и вектор b, но вдвое короче.
# Также вывести направляющие косинусы вектора b и направляющие косинусы вектора с2 = (a-b)

a = np.array([3, -2, 6])
b = np.array([-2, 1, 0])

# ваш код

c1 = a + b
c2 = a - b
c3 = -2 * a
c4 = b / 2

print(*(round(np.linalg.norm(v), 2) for v in (a, c1, c3 + c4)))
print(*(np.round(v / np.linalg.norm(v), 2) for v in (b, c2)))

7.0 6.16 14.6
[-0.89  0.45  0.  ] [ 0.6  -0.36  0.72]


In [22]:
# Задача № 16
# Дано координаты векторов a и b
# Выход: скалярное произведение векторов a и b

a = np.array([1, 1, 1])
b = np.array([1, 1, 1])

# ваш код

print(a.dot(b))

3


In [23]:
# Задача № 17
# Дано координаты векторов a и b
# Выход: косинус угла между этими векторами

a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

# ваш код

print(round(a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b)), 3))

0.0


In [24]:
# Задача № 18
# Дано координаты векторов a и b
# Выход: вычислить проекцию вектора a на вектор b

a = np.array([1, 1])
b = np.array([1, 0])

# ваш код

print(round(a.dot(b)/np.linalg.norm(b), 2))

1.0


In [26]:
# Задача № 19
# Дано координаты векторов a и b в ортонормированном базисе
# Выход: координаты векторного произведения векторов a и b

a = np.array([1, 0, 0])
b = np.array([0, 0, 1])

# ваш код

print(np.cross(a, b))

[ 0 -1  0]


In [27]:
# Задача № 20
# Дано координаты векторов a и b в ортонормированном базисе
# Выход: вычислить модуль векторного произведения

a = np.array([1, 0, 0])
b = np.array([0, 0, 1])

# ваш код

print(np.linalg.norm(np.cross(a, b)))

1.0


In [29]:
# Задача № 21
# Дано координаты векторов a и b в ортонормированном базисе
# Выход: вычислить синус угла между векторами

a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

# ваш код

sin_a = np.linalg.norm(np.cross(a, b)) / (np.linalg.norm(a) * np.linalg.norm(b))
print(sin_a)

1.0


In [30]:
# Задача № 22
# Дано координаты векторов a и b в ортонормированном базисе
# Выход: True, если вектора коллинеарны, False в противном случае

a = np.array([1, 0, 0])
b = np.array([-3, 0, 0])

# ваш код

print(np.cross(a, b).mean() == 0)

True


In [31]:
# Задача № 22
# Дано координаты векторов a, b, c
# Выход: вычислить скалярное произведение a и векторного произведения b, c

a = np.array([1, 2, 0])
b = np.array([2, 1, 3])
c = np.array([0, 2, 1])

# ваш код

print(a.dot(np.cross(b, c)))

-9


In [32]:
# Задача № 23
# Дано координаты векторов a, b, c
# Выход: вычислить векторное произведение a и векторного произведения b, c

a = np.array([3, 2, 1])
b = np.array([-1, 2, 0])
c = np.array([0, 2, 3])

# ваш код

result = np.cross(a, np.cross(b, c))
print(result)

[-7 12 -3]


In [33]:
# Задача № 24
# Дано координаты векторов a, b, c
# Выход: вычислить модуль векторного произведения a и векторного произведения b, c

a = np.array([-1, 0, 0])
b = np.array([0, 1, 0])
c = np.array([0, 0, -2])

# ваш код

result = np.linalg.norm(np.cross(a, np.cross(b, c)))
print(result)

0.0


In [34]:
# Задача № 25
# Дано координаты векторов a, b, c
# Выход: True если векторы образуют ортогональный базис, иначе - False

a = np.array([1, 0, 0])
b = np.array([0, -1, 0])
c = np.array([0, 0, 3])

# ваш код

result = np.cross(a, np.cross(b, c))
print(result.mean()==0)

True


In [35]:
# Задача № 26
# Дано координаты векторов a, b, c
# Выход: True если векторы компланарны, иначе - False

a = np.array([1, 1, 0])
b = np.array([1, 1, 1])
c = np.array([1, -1, 1])

# ваш код

result = np.dot(a, np.cross(b, c))
print(result==0)

False


In [44]:
# Задача № 27
# Дано координаты точек A, B, вектора a
# Выход: 1. Координаты вектора AB, который указывает направление от точки A до точки B
#        2. модуль вектора AB
#        3. Направляющие косинусы вектора AB, показывающие отношение проекций вектора AB на координатные оси к его длине
#        4. Координаты точки C, с которой совпадает конец вектора a, если его начало совпадает с точкой B

A = np.array([1, -2, 0])
B = np.array([-2, 3, -1])
a = np.array([0, 1, 2])

# ваш код

AB = B-A
nAB = np.linalg.norm(AB)
cos_ab = AB/nAB
C = a+B
print(AB)
print(nAB)
print(cos_ab)
print(C)


[-3  5 -1]
5.916079783099616
[-0.50709255  0.84515425 -0.16903085]
[-2  4  1]


In [46]:
# Задача № 28
# Дано модуль вектора a, углы в градусах, которые этот вектор составляет с осями x, y, z
# Выход: проекции вектора a на соответствующие оси

mod_a = 3
angle_x = 45
angle_y = 60
angle_z = 120

# ваш код

result_1 = mod_a*np.cos(np.deg2rad(angle_x)) 
result_2 = mod_a*np.cos(np.deg2rad(angle_y))
result_3 = mod_a*np.cos(np.deg2rad(angle_z))
print(result_1, result_2, result_3)

2.121320343559643 1.5000000000000004 -1.4999999999999993


In [2]:
# Задача № 29
# Дано три числа a, b, c - углы в градусах, которые гипотетический вектор составляет с осями координат
# Выход: True - если такое возможно, False в противном случае

a = 0
b = 90
c = 90

# ваш код

print((a+b+c) == 180)

True


In [3]:
# Задача № 30
# Дано координаты векторов a и b
# Выход: вычислить модуль a+b и сумму модулей |a|+|b|

a = np.array([1, 2, 1])
b = np.array([2, 1, 2])

# ваш код

res1 = np.linalg.norm(a+b)
res2 = np.linalg.norm(a) + np.linalg.norm(b)
print(res1, res2)

5.196152422706632 5.449489742783178


In [7]:
# Задача № 31
# Дано три числа проекции вектора силы
# Выход: модуль силы, углы в градусах которые, этот вектор образует с осями координат

a = 4
b = 2
c = -3

# ваш код

vec = np.array((a, b, c))
mod_vec = np.linalg.norm(vec)
angle_x = np.rad2deg(np.arccos(a/mod_vec))
angle_y = np.rad2deg(np.arccos(b/mod_vec))
angle_z = np.rad2deg(np.arccos(c/mod_vec))
print(mod_vec)
print(angle_x, angle_y, angle_z)

5.385164807134504
42.03111377419729 68.19859051364818 123.85451481262052


In [8]:
# Задача № 32
# Дано координаты векторов a и b
# Выход: 1. True если вектора коллинеарны, False в противном случае.
#        2. Число, показывающее во сколько раз отличается длина вектора а от длины вектора b.
#        3. True если вектора направлены противоположно, иначе False

a = np.array([3, 0, 0])
b = np.array([-5, 0, 0])

# ваш код

cross_a_b = np.cross(a, b)
if cross_a_b.mean() == cross_a_b[0]:
    res1 = True
else:
    res1 = False
l_a = np.linalg.norm(a)
l_b = np.linalg.norm(b)
res2 = l_a/l_b
if a.dot(b)/(l_a*l_b) == -1:
    res3 = True
else:
    res3 = False
print(res1)
print(res2)
print(res3)

True
0.6
True


In [9]:
# Задача № 33
# Дано координаты точек A и B
# Выход: координаты орт вектора, направленного также как вектор AB

A = np.array([-1, 2, 3])
B = np.array([0, 1, -2])

# ваш код

AB = B-A
res = AB/np.linalg.norm(AB)
print(res)

[ 0.19245009 -0.19245009 -0.96225045]


In [12]:
# Задача № 34
# Дано координаты векторов а, p, q, лежащих в одной плоскости
# Выход: координаты вектора а в базисе {p, q}

a = np.array([3, -2])
p = np.array([-2, 1])
q = np.array([7, -4])

# ваш код

k = np.array(([p[0], q[0]], [p[1], q[1]]))
res = np.linalg.solve(k, a)
print(res)

[2. 1.]


In [13]:
# Задача № 35
# Дано координаты векторов а, b, c, лежащих в одной плоскости
# Выход: 1. True если а можно разложить по {b, c}, в противном случае False 
#        2. True если b можно разложить по {a, c}, в противном случае False 
#        3. True если c можно разложить по {a, b}, в противном случае False

a = np.array([1, -5])
b = np.array([-1, 5])
c = np.array([2, 3])

# ваш код

res1 = np.linalg.det(np.array((b, c)).transpose())
res2 = np.linalg.det(np.array((a, c)).transpose())
res3 = np.linalg.det(np.array((a, b)).transpose())
print(res1 != 0, res2 != 0, res3 != 0)

True True False


In [14]:
# Задача № 36
# Дано координаты векторов p, q, r, a
# Выход: координаты вектора a в базисе {p, q, r}

p = np.array([3, -2, 4])
q = np.array([-2, 1, 3])
r = np.array([7, -4, 1])
a = np.array([25, -15, 14])

# ваш код

k = np.array((p, q, r)).transpose()
res = np.linalg.solve(k, a)
print(res)

[2. 1. 3.]


In [15]:
# Задача № 37
# Дано координаты векторов а, b и с
# Выход: True если вектора линейно зависимы, False в противном случае

a = np.array([1, 2, 0])
b = np.array([3, -4, 0])
c = np.array([12, 4, 0])

# ваш код

k = np.array((a, b, c)).transpose()
res = np.linalg.det(k)
print(res == 0)

True


In [16]:
# Задача № 38
# Дано координаты векторов а, b - стороны треугольника ABC, координаты точки A
# Выход: координаты точки О - точки пересечения медиан треугольника АВС

a = np.array([0, 1, 3])
b = np.array([2, 0, 1])
A = np.array([1, 2, 3])

# ваш код

AO = (1/3) * (a+b)
O = A + AO
print(O)

[1.66666667 2.33333333 4.33333333]


In [3]:
# Задача № 39
# Дано координаты векторов a, b и c
# Выход: 1. Скалярное произведение векторов a, b
#        2. Векторное произведение векторов a, b и его модуль
#        3. Смешанное произведение векторов a, b, c
#        4. Двойное векторное произведение a(b, c) и его модуль

a = np.array([-1, 0, -3])
b = np.array([4, -3, 2])
c = np.array([0, -1, 0])

# ваш код

res1 = a.dot(b)
res2 = np.cross(a, b)
res2_m = np.linalg.norm(res2)
res3 = a.dot(np.cross(b, c))
res4 = np.cross(a, np.cross(b, c))
res4_m = np.linalg.norm(res4)
print(res1)
print(res2, res2_m)
print(res3)
print(res4, res4_m)

-10
[ -9 -10   3] 13.784048752090222
10
[  0 -10   0] 10.0


In [4]:
# Задача № 40
# Дано координаты векторов a, b и c
# Выход: результат выражения (2a - b)*c

a = np.array([-1, 0, -3])
b = np.array([2, 1, 1])
с = np.array([0, -1, 0])

# ваш код

res = (2*a-b).dot(c)
print(res)

1


In [7]:
# Задача № 41
# Дано координаты векторов a, b и c
# Выход: проекция вектора (a+b) на вектор c

a = np.array([3, 2, 0])
b = np.array([-1, 1, 3])
c = np.array([3, -2, 1])

# ваш код

ab = a+b
ab_m = np.linalg.norm(ab)
c_m = np.linalg.norm(c)
cos_a = ab.dot(c) / (ab_m*c_m)
res = ab_m * cos_a
print(res)

0.8017837257372731


In [8]:
# Задача № 42
# Дано координаты точек треугольника А, В и С
# Выход: внутренний угол треугольника при вершине С

A = np.array([2, 5, 3])
B = np.array([-3, 0, -1])
C = np.array([-4, 3, -1])

# ваш код

a = A-C
b = B-C
cos_c = a.dot(b) / (np.linalg.norm(a)*np.linalg.norm(b))
res = np.degrees(np.arccos(cos_c))
print(res)

90.0


In [9]:
# Задача № 43
# Дано координаты точек четырехугольника А, В, С, D
# Выход: True если диагонали четырехугольника перпендикулярны, False в противном случае

A = np.array([1, -2, 2])
B = np.array([1, 4, 0])
C = np.array([-4, 1, 1])
D = np.array([-5, -5, 3])

# ваш код

AC = C-A
BD = D-B
res = np.rad2deg(np.arccos(AC.dot(BD) / (np.linalg.norm(AC) * np.linalg.norm(BD))))
print(res==90)

True


In [ ]:
# Задача № 44
# Дано модули векторов a, b и величина их скалярного произведения
# Выход: модуль векторного произведения векторов a, b

a_m = 10
b_m = 2
mult_ab = 12

# ваш код

sin_a = (1 - (mult_ab/(a_m*b_m))**2)**0.5
res = a_m*b_m*sin_a
print(res)

16.0


In [11]:
# Задача № 45
# Дано модули векторов a, b и угол между ними в градусах
# Выход: квадрат векторного произведения векторов a, b

a_m = 1
b_m = 2
angle_ab = 120

# ваш код

res = (a_m*b_m*np.sin(np.deg2rad(angle_ab)))**2
print(res)

3.0000000000000004


In [12]:
# Задача № 46
# Дано координаты точек А, В, С
# Выход: координаты векторного произведения между векторами BC - 2CA x CB

A = np.array([2, -1, 2])
B = np.array([1, 2, -1])
C = np.array([3, 2, 1])

# ваш код

BC = C-B
CA = A-C
CB = B-C
res = BC - np.cross(2*CA, CB)
print(res)

[-10   8  14]


In [14]:
# Задача № 47
# Дано модули векторов a и b и угол в градусах между ними
# Выход: Площадь треугольника, построенного на векторах a-2b и 3a+2b

a_m = 5
b_m = 5
angle_ab = 45

# ваш код

s_one = 0.5 * a_m * 2*b_m * np.sin(np.deg2rad(angle_ab))
s_two = 0.5 * 3*a_m * 2*b_m * np.sin(np.deg2rad(180-angle_ab))
s = s_one + s_two
print(s)

70.71067811865476


In [15]:
# Задача № 48
# Дано проекции вектора силы F и координаты точки А приложения силы
# Выход: момент вектора силы, приложенной к точке A относительно начала координат (M = OA × F)

F = np.array([3, 2, -4])
A = np.array([2, -1, 1])

# ваш код

O = np.array((0, 0, 0))
OA = O-A
M = np.cross(F, OA)
print(M)

[ 2 11  7]


In [16]:
# Задача № 49
# Дано координаты точек пирамиды А, В, С, D
# Выход: объем пирамиды

A = np.array([2, 2, 2])
B = np.array([4, 3, 3])
C = np.array([4, 5, 4])
D = np.array([5, 5, 6])

# ваш код

AB = B-A
AC = C-A
AD = D-A
v_par = AB.dot(np.cross(AC, AD))
res = abs(round(v_par/6, 2))
print(res)

1.17


In [17]:
# Задача № 50
# Дано координаты векторов b, c, d
# Выход: True если вектора компланарны, False в обратном случае

b = np.array([-1, 3, 2])
c = np.array([2, -3, -4])
d = np.array([-3, 12, 6])

# ваш код

if b.dot(np.cross(c, d)) == 0:
    print(True)
else:
    print(False)

True


In [18]:
# Задача № 51
# Дано координаты векторов в пятимерном ортонормированном базисе
# Выход: скалярное произведение в этом базисе, модуль вектора а, модуль вектора b

a = np.array([1, -2, 0, 0, 1])
b = np.array([0, 3, 1, -1, 2])

# ваш код

res1 = a.dot(b)
res2 = np.linalg.norm(a)
res3 = np.linalg.norm(b)
print(res1)
print(res2)
print(res3)

-4
2.449489742783178
3.872983346207417


In [19]:
# Задача № 52
# Дано координаты векторов a, b и c
# Выход: проекция векторного произведения a и b на направление вектора c

a = np.array([2, 3, -1])
b = np.array([1, 9, -11])
c = np.array([1, -1, 0])

# ваш код

mult_ab = np.cross(a, b)
cos_a = mult_ab.dot(c) / (np.linalg.norm(mult_ab) * np.linalg.norm(c))
res = np.linalg.norm(mult_ab)*cos_a
print(res)

-31.819805153394636


In [ ]:
# Задача № 53
# Дано координаты векторов а и b, лежащие в одной плоскости, модуль искомого вектора |с|, перпендикулярного векторам a и b
# Выход: координаты вектора с, при условии, что он образовывает тупой угол с осью z

a = np.array([1, 2, 1])
b = np.array([-5, 4, 0])
c_m = 4

# ваш код

oz = np.array((0, 0, 1))
ab = np.cross(a, b)

if oz.dot(ab) >= 0:
    ab = np.cross(b, a)
res = c_m / np.linalg.norm(ab) * ab
print(res)

[ 1.03931168  1.2991396  -3.63759089]


In [22]:
# Задача № 55
# Дано координаты точек A, B, C, D
# Выход: True если точки лежат в одной плоскости, False в противном случае

A = np.array([2, -1, -2])
B = np.array([1, 2, 1])
C = np.array([2, 3, 0])
D = np.array([5, 0, -6])

# ваш код

AB = B-A
AC = C-A
AD = D-A
res = AB.dot(np.cross(AC, AD))
print(res == 0)

True


In [24]:
# Задача № 56
# Дано координаты точек A, B, D параллелограмма ABCD
# Выход: угол COD между диагоналями этого параллелограмма

A = np.array([1, 2, 0])
B = np.array([-2, 1, 1])
D = np.array([3, -1, 3])

# ваш код

AB = B-A
AD = D-A
c = AB + AD
d = AD - AB
COD = np.rad2deg(np.arccos(c.dot(d) / (np.linalg.norm(c) * np.linalg.norm(d))))
print(COD)

70.52877936550931


In [25]:
# Задача № 57
# Дано координаты векторов a, b
# Выход: проекция вектора b на вектор a, угол между векторами в градусах

a = np.array([2, 2, 1])
b = np.array([6, 3, 2])

# ваш код

res1 = a.dot(b) / np.linalg.norm(a)
res2 = np.rad2deg(np.arccos(a.dot(b) / (np.linalg.norm(a)*np.linalg.norm(b))))
print(res1)
print(res2)

6.666666666666667
17.75279016194669


In [27]:
# Задача № 58
# Дано координаты вектора с, модуль вектора р. Вектор р противоположно направлен вектору с.
# Выход: проекция вектора b на вектор a, угол между векторами в градусах

c = np.array([16, -15, 12])
p_m = 75

# ваш код

c_m = np.linalg.norm(c)
res = -p_m/c_m*c
print(res)

[-48.  45. -36.]


In [28]:
# Задача № 59
# Дано координаты вершин треугольника АВС
# Выход: длина АК - высота треугольника АВС

A = np.array([2, 2, 2])
B = np.array([4, 0, 3])
C = np.array([0, 1, 0])

# ваш код

ab = np.linalg.norm(B-A)
ac = np.linalg.norm(C-A)
bc = np.linalg.norm(C-B)
pp = 0.5*(ab+ac+bc)
s = (pp*(pp-ab)*(pp-ac)*(pp-bc))**0.5
h = 2*s / np.linalg.norm(bc)
print(h)

1.58113883008419


In [30]:
# Задача № 60
# Дано координаты точек A, B, C, D вершины пирамиды
# Выход: объем пирамиды ABCD

A = np.array([0, 0, 1])
B = np.array([2, 3, 5])
C = np.array([6, 2, 3])
D = np.array([3, 7, 2])

# ваш код

AB = B-A
AC = C-A
AD = D-A
v_par = AB.dot(np.cross(AC, AD))
res = abs(v_par/6)
print(res)

20.0


In [31]:
# Задача № 61
# Дано координаты точек A, B, C, D вершины пирамиды
# Выход: длина высоты, опущенной на грань ВСD

A = np.array([2, 1, 0])
B = np.array([2, -1, 2])
C = np.array([0, 1, 3])
D = np.array([-1, 1, 0])

# ваш код

AB = B-A
AC = C-A
AD = D-A
v_pir = AB.dot(np.cross(AC, AD))/6
ab = np.linalg.norm(C-B)
ac = np.linalg.norm(D-B)
ad = np.linalg.norm(C-D)
pp = 0.5*(ab+ac+ad)
s_osn = (pp*(pp-ab)*(pp-ac)*(pp-ad))**0.5
h = 3*v_pir/s_osn
print(h)

1.907996184011448


In [32]:
# Задача № 62
# Дано координаты точек A, B, C, D
# Выход: True, если точки лежат в одной плоскости, False в противном случае

A = np.array([5, 7, -2])
B = np.array([3, 1, -1])
C = np.array([9, 4, -4])
D = np.array([1, 5, 0])

# ваш код

res = (B-A).dot(np.cross((C-A), (D-A)))
print(res==0)

True


In [ ]:
# Задача № 63
# Дано координаты вектора a
# Выход: углы в градусах, которые вектор образует с осями координат ох, оу, оz

a = np.array([1, 1, 0])

# ваш код

a_m = np.linalg.norm(a)
angle_a = np.rad2deg(np.arccos(a[0]/a_m))
angle_b = np.rad2deg(np.arccos(a[1]/a_m))
angle_c = np.rad2deg(np.arccos(a[2]/a_m))
print(angle_a, angle_b, angle_c)

45.00000000000001 45.00000000000001 90.0


In [36]:
# Задача № 64
# Дано модуль вектора a и углы, который он образует с осями ох и оу
# Выход: возможный угол в градусах, который этот вектор образует с осью оz

a_m = 2
angle_x = 60
angle_y = 150

# ваш код

angle_x = np.deg2rad(float(angle_x))
angle_y = np.deg2rad(float(angle_y))
cos_xy = abs(1 - np.cos(angle_x)**2 - np.cos(angle_y)**2)
angle_z = round(np.rad2deg(np.arccos(2*cos_xy - 1)*0.5), 2)
print(angle_z)

90.0


In [37]:
# Задача № 65
# Дано координаты точек A, B, C, D
# Выход: True, если фигура ABCD - трапеция с основаниями BC и DA

A = np.array([0, 0, 0])
B = np.array([1, 3, 0])
C = np.array([3, 3, 0])
D = np.array([5, 0, 0])

# ваш код

a = D-A
b = C-B
c = B-A
d = C-D
res_t = abs(c.dot(d) / (np.linalg.norm(c)*np.linalg.norm(d)))
res = abs(a.dot(b) / (np.linalg.norm(a)*np.linalg.norm(b)))
if res_t != 1 and res == 1:
    print(True)
else:
    print(False)

True


In [39]:
# Задача № 66
# Дано координаты векторов a, b и c на плоскости
# Выход: коэффициенты разложения вектора p=a+b+c по базису {a, b}

a = np.array([3, -1])
b = np.array([1, -2])
c = np.array([-1, 7])

# ваш код

p = a+b+c
k = list([a[i], b[i]] for i in range(len(a)))
res = np.linalg.solve(k, p)
print(res)

[ 2. -3.]


In [40]:
# Задача № 67
# Дано координаты точек А и В
# Выход: координаты точек С и D, которые делят отрезок между точками А и В на три равные части

A = np.array([3, -5, 2])
B = np.array([5, -3, 1])

# ваш код

ab = np.linalg.norm(B-A)
C = (2/(1+2))*A + (1/(1+2))*B
D = (1/(1+2))*A + (2/(1+2))*B
print(C)
print(D)

[ 3.66666667 -4.33333333  1.66666667]
[ 4.33333333 -3.66666667  1.33333333]


In [41]:
# Задача № 68
# Дано координаты точек A, B, C
# Выход: векторное произведение ABxBC

A = np.array([2, -1, 2])
B = np.array([1, 2, -1])
C = np.array([3, 2, 1])

# ваш код

res = np.cross(B-A, C-B)
print(res)

[ 6 -4 -6]


In [43]:
# Задача № 69
# Дано координаты точек A, B, C, D
# Выход: True если фигура ABCD квадрат, False в противном случае

A = np.array([-5, 3, 4])
B = np.array([-1, -7, 5])
C = np.array([6, -5, -3])
D = np.array([2, 5, -4])

# ваш код

a = np.linalg.norm(B-A)
b = np.linalg.norm(C-B)
c = np.linalg.norm(D-C)
d = np.linalg.norm(D-A)
print(a == b == c == d)

True
