Варианты решения задач

In [2]:
import numpy as np

In [5]:
# Задача № 1 
# Выход: Создайте одномерный массив из 5 целых чисел от 0 до 4

# ваш код

array = np.linspace(0, 4, 5, dtype=int)
print(array)

[0 1 2 3 4]


In [6]:
# Задача № 2
# Выход: Создайте двумерный массив размером 4x5, заполненный нулями

# ваш код

array = np.zeros((4, 5))
print(array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
# Задача № 3
# Выход: Создайте массив размером 3x2, заполненный единицами

# ваш код

array = np.ones((3, 2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Задача № 4
# Выход: Создайте одномерный массив из четных чисел от 0 до 8 (включительно) с шагом 2

# ваш код

array = np.arange(0, 9, 2)
print(array)

[0 2 4 6 8]


In [9]:
# Задача № 5
# Выход: Создайте массив из 5 равномерно распределенных значений между 0 и 1, включая обе границы

# ваш код

array = np.linspace(0, 1, num=5, endpoint=True)
print(array)

[0.   0.25 0.5  0.75 1.  ]


In [10]:
# Задача № 6
# Выход: Создайте массив размером 2x3, заполненного значением 7

# ваш код

array =  np.full((2, 3), 7)
print(array)

[[7 7 7]
 [7 7 7]]


In [11]:
# Задача № 7
# Выход: Создайте массив из 5 строк и 2 столбцов, содержащий только булевы значения True

# ваш код

array = np.full((5, 2), True)
print(array)

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


In [29]:
# Задача № 8
# Выход: Создайте трехмерный массив (каждый массив должен содержать две строки и
#        четыре столбца) и определите его количество измерений

# ваш код

arr = np.zeros((3, 2, 4)) 
dimensions = arr.ndim 
print(arr, "\n")
print("Количество измерений:", dimensions)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]] 

Количество измерений: 3


In [21]:
# Задача № 9
# Выход: Создайте матрицу 3x4 заполненную единицами и определите её размеры

# ваш код

matrix = np.ones((3, 4)) 
matrix_shape = matrix.shape
print("Матрица:")
print(matrix, "\n")
print("Размеры матрицы:", matrix_shape)

Матрица:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

Размеры матрицы: (3, 4)


In [23]:
# Задача № 10
# Выход: Создайте квадратную матрицу 4x4 с единицами на главной диагонали

# ваш код

identity_matrix = np.identity(4)
print("Квадратная матрица:")
print(identity_matrix)

Квадратная матрица:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Задача № 11
# Выход: Повторите созданный массив с элементами (1, 2, 3) 3 раза, чтобы получить в итоге такой массив

# ваш код

original_array = np.array([1, 2, 3])
tiled_array = np.tile(original_array, (3, 1))
print("Исходный массив:")
print(original_array, "\n")
print("Массив с повторенными элементами:")
print(tiled_array)

Исходный массив:
[1 2 3] 

Массив с повторенными элементами:
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# Задача № 12
# Выход: Повторите созданный массив с элементами (1, 2, 3) 4 раза вдоль оси 0 (строки)
#        и дополнительно, каждую строку массива увеличьте по размеру в два раза с те же элементами
#        (вдоль оси 1(столбцы))

# ваш код

original_array = np.array([1, 2, 3])
tiled_array =  np.tile(original_array, (4, 2))
print("Исходный массив:")
print(original_array, '\n')
print("Массив с повторенными элементами:")
print(tiled_array)

Исходный массив:
[1 2 3] 

Массив с повторенными элементами:
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]


In [ ]:
# Задача № 13
# Выход: Повторите созданный массив с элементами (1, 2, 3) 4 раза вдоль оси 0 (строки)
# и дополнительно, каждую строку массива увеличьте по размеру в два раза с те же
# элементами (вдоль оси 1 (столбцы)), и еще, дополнительно, сделайте этот массив двумерным

# ваш код

original_array = np.array([1, 2, 3])
tiled_array = np.tile(original_array, (2, 4, 2))
print("Исходный массив:")
print(original_array, '\n')
print("Массив с повторенными элементами:")
print(tiled_array)

Исходный массив:
[1 2 3] 

Массив с повторенными элементами:
[[[1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]]

 [[1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]]]


In [ ]:
# Задача № 14
# Дано: У вас есть массив arr с целыми числами.
# Выход: Напишите программу для определения текущего типа данных элементов массива

# ваш код

current_dtype = arr.dtype
print("Исходный массив:", arr)
print("Текущий тип данных:", current_dtype)

Исходный массив: [1 2 3 4]
Текущий тип данных: int32


In [30]:
# Задача № 15
# Выход: создать массив arr с числами от 1 до 3, включительно, и указать явно тип данных целых чисел

# ваш код

arr = np.arange(1, 4, dtype=int) 
print("Массив целых чисел:", arr)
print("Тип данных:", arr.dtype)

Массив целых чисел: [1 2 3]
Тип данных: int32


In [ ]:
# Задача № 16
# Дано: массив arr_float с вещественными числами 
# Выход: напишите программу для создания нового массива arr_int, в котором вещественные числа будут округлены до целых

arr_float = np.array([1.2, 2.5, 3.8, 4.1])

# ваш код

arr_int = arr_float.astype(int)
print("Исходный массив:", arr_float)
print("Тип данных:", arr_float.dtype, '\n')
print("Массив округленных целых чисел:", arr_int)
print("Тип данных:", arr_int.dtype)

Исходный массив: [1.2 2.5 3.8 4.1]
Тип данных: float64 

Массив округленных целых чисел: [1 2 3 4]
Тип данных: int32


In [30]:
# Задача № 17
# Дано: два датасета с данными о температуре и влажности. Каждый датасет представлен в виде двумерного массива,
#       где строки представляют дни, а столбцы представляют конкретные моменты времени в течение дня.
#       Тип данных - int. Вам нужно изменить их на float.
# Выход: 1. Создайте функцию, которая принимает на вход два аргумента: dataset и new_dtype.
#        2. Используйте функцию для изменения типа данных каждого датасета на тип float.

# Датасет температуры (тип данных: int)
temp_data = np.array([[22, 25, 24, 23, 21],
                      [20, 18, 19, 22, 24]])

# Датасет влажности (тип данных: int)
humid_data = np.array([[45, 50, 48, 52, 47],
                       [45, 48, 50, 51, 53]])

# ваш код


def change_data_type(dataset, new_dtype):
    return dataset.astype(new_dtype) 

temp_data = change_data_type(temp_data, float)
humid_data = change_data_type(humid_data, float)

print(f'Новый тип данных temp_data: {temp_data.dtype}')
print(f'Новый тип данных humid_data: {humid_data.dtype}')

Новый тип данных temp_data: float64
Новый тип данных humid_data: float64


In [36]:
# Задача № 18
# Выход: Выполните поэлементное сложение двух массивов arr1 и arr2 и выведите результат на экран

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[3, 2, 1]])

# ваш код

result_add = arr1 + arr2
print(result_add)

[[4 4 4]]


In [37]:
# Задача № 19
# Выход: Выполните поэлементное умножение двух массивов arr1 и arr2 и выведите результат на экран

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

# ваш код

result_multiply = arr1 * arr2
print(result_multiply)

[[ 7 16 27]
 [40 55 72]]


In [38]:
# Задача № 20
# Выход: Выполните поэлементное деление массива на 2 и сохраните результат в result_divide

arr1 = np.array([[8, 8, 4], 
                 [4, 2, 2], 
                 [10, 10, 2]])

# ваш код

result_divide = arr1 / 2
print(result_divide)

[[4. 4. 2.]
 [2. 1. 1.]
 [5. 5. 1.]]


In [39]:
# Задача № 21
# Выход: Выполните поэлементное сложение двух массивов и сохраните результат в массив result_add

arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])

arr2 = np.array([[9, 8, 7], 
                 [6, 5, 4], 
                 [3, 2, 1]])

# ваш код

result_add = arr1 + arr2
print(result_add)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [40]:
# Задача № 22
# Выход: Выполните поэлементное вычитание arr1 из arr2 и сохраните результат в массив result_subtract

arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])

arr2 = np.array([[10, 11, 12], 
                 [13, 14, 15], 
                 [16, 17, 18]])

# ваш код

result_subtract = arr1 - arr2
print(result_subtract)

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [41]:
# Задача № 23
# Выход: Возведите все элементы массива в квадрат и сохраните результат в result_double

arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])

# ваш код

result_double = arr1 ** 2
print(result_double)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [42]:
# Задача № 24
# Дано: массив grades из оценок студентов (от 0 до 100).
# Выход: Преобразуйте тип данных массива grades на float, затем напишите код, который увеличит все оценки более 50 на 10%

grades = np.array([75, 45, 60, 90, 30, 85, 40])

# ваш код

grades = grades.astype(float)
grades = np.where(grades>50, grades*1.1, grades)
print(grades)

[82.5 45.  66.  99.  30.  93.5 40. ]


In [ ]:
# Задача № 25
# Выход: Выполните умножение вектора (vector) на скаляр (scalar)

vector = np.array([1, 2, 3, 4])
scalar = 2

# ваш код

result = vector * scalar
print(result)

[2 4 6 8]


In [44]:
# Задача № 26
# Дано: массив prices из цен на товары
# Выход: напишите код, который уменьшит цены на 10% для товаров с ценой выше 40

prices = np.array([50, 30, 70, 40, 90], float)

# ваш код

prices = np.where(prices>40, prices*0.9, prices)
print(prices)

[45. 30. 63. 40. 81.]


In [45]:
# Задача № 27
# Выход: выполните сложение матрицы и вектора

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

vector = np.array([0, 1, 2])

# ваш код

result = matrix + vector
print(result)

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [31]:
# Задача № 28
# Выход: выполните умножение матриц matrix_a и matrix_b. Создайте matrix_b с такими значениями,
#        чтобы получить в итоге умножения такую матрицу:
# [[ 10  20  30]
# [ 80 100 120]
# [210 240 270]]

matrix_a = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])

# ваш код

matrix_b = [[10], [20], [30]]
result = matrix_a * matrix_b
print(result)

[[ 10  20  30]
 [ 80 100 120]
 [210 240 270]]


In [ ]:
# Задача № 29
# Выход: выполните вычитание матриц matrix_c и matrix_d.
#        Создайте matrix_d с такими значениями, чтобы получить в итоге вычитания такую матрицу:
# [[ 9 18 27]
# [39 48 57]
# [69 78 87]]

matrix_c = np.array([[10, 20, 30], 
                     [40, 50, 60], 
                     [70, 80, 90]])

# ваш код

matrix_d = [1, 2, 3]
result = matrix_c - matrix_d
print(result)

[[ 9 18 27]
 [39 48 57]
 [69 78 87]]


In [ ]:
# Задача № 30
# Выход: выполните умножение матриц matrix_e и matrix_f. Создайте matrix_f с такими значениями,
#        чтобы получить в итоге умножения такую матрицу:
# [[ 2 8]
# [18 32]]

matrix_e = np.array([[2, 4], 
                     [6, 8]])

# ваш код

matrix_f = [[1, 2], [3, 4]]
result = matrix_e * matrix_f
print(result)

[[ 2  8]
 [18 32]]


In [52]:
# Задача № 31
# Выход: выведите первый и последний элементы с помощью срезов

arr = np.array([1, 2, 3, 4, 5])

# ваш код

arr1 = arr[0]
arr2 = arr[-1]
print(f'Первый элемент: {arr1}')  
print(f'Последний элемент: {arr2}')

Первый элемент: 1
Последний элемент: 5


In [53]:
# Задача № 32
# Выход: выведите вторую строку и третий столбец с помощью срезов

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

# ваш код

arr1 = arr[1, :] 
arr2 = arr[:, 2]
print(f'Вторая строка: {arr1}')  
print(f'Третий столбец: {arr2}')

Вторая строка: [4 5 6]
Третий столбец: [3 6 9]


In [54]:
# Задача № 33
# Выход: выведите первый слой, вторую строку и первый столбец с помощью срезов

arr = np.array([[[1, 2], 
                 [3, 4]], 
                [[5, 6], 
                 [7, 8]], 
                [[9, 10], 
                 [11, 12]]])

# ваш код

arr1 = arr[0, :, :]
arr2 = arr[0, 1, :]
arr3 = arr[0, :, 0]
print(f'Первый слой:\n{arr1}')  
print(f'Вторая строка первого слоя: {arr2}')  
print(f'Первый столбец первого слоя: {arr3}')

Первый слой:
[[1 2]
 [3 4]]
Вторая строка первого слоя: [3 4]
Первый столбец первого слоя: [1 3]


In [55]:
# Задача № 34
# Выход: выведите все элементы в четных столбцах

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# ваш код

arr1 = arr[:, 1::2]
print(f'Элементы с четными столбцами:\n{arr1}')

Элементы с четными столбцами:
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [56]:
# Задача № 35
# Выход: выведите все элементы в нечетных столбцах

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# ваш код

arr1 = arr[:, ::2]
print(f'Элементы с нечетными столбцами:\n{arr1}')

Элементы с нечетными столбцами:
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [57]:
# Задача № 36
# Выход: выведите все элементы с нечетными строками

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# ваш код

arr1 = arr[::2, :]
print(f'Элементы с нечетными строками:\n{arr1}')

Элементы с нечетными строками:
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [58]:
# Задача № 37
# Выход: выделите подматрицу, состоящую из трех последних строк и двух первых столбцов

matrix = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25]])

# ваш код

submatrix = matrix[-3:, :2]
print(f'Матрица трех последних строк и двух первых столбцов:\n{submatrix}')

Матрица трех последних строк и двух первых столбцов:
[[11 12]
 [16 17]
 [21 22]]


In [59]:
# Задача № 38
# Выход: выделите подматрицу, состоящую из второй и третьей строк, а также третьего и четвёртого столбцов

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

# ваш код

submatrix = matrix[1:3, 2:]
print(f'Матрица из второй и третьей строк, а также третьего и четвёртого столбцов:\n{submatrix}')

Матрица из второй и третьей строк, а также третьего и четвёртого столбцов:
[[ 7  8]
 [11 12]]


In [61]:
# Задача № 39
# Выход: выведите подматрицу, состоящую из элементов с индексами от 1 до 2 по обеим осям, с помощью срезов

arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12], 
                [13, 14, 15, 16]])

# ваш код

submatrix = arr[1:3, 1:3]
print(f'Подматрица, состоящая из элементов с индексами от 1 до 2 по обеим осям:\n{submatrix}')

Подматрица, состоящая из элементов с индексами от 1 до 2 по обеим осям:
[[ 6  7]
 [10 11]]


In [62]:
# Задача № 40
# Выход: выведите элементы в обратном порядке с шагом 2 с помощью срезов

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# ваш код

submatrix = arr[::-2]
print(f'Элементы в обратном порядке с шагом 2:\n{submatrix}')

Элементы в обратном порядке с шагом 2:
[10  8  6  4  2]


In [63]:
# Задача № 41
# Выход: выберите подматрицу 2x2 в верхнем левом углу для каждой матрицы

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код

result = tensor[:, :2, :2]
print(f'Подматрица 2x2 в верхнем левом углу для каждой матрицы:\n{result}')

Подматрица 2x2 в верхнем левом углу для каждой матрицы:
[[[ 1  2]
  [ 4  5]]

 [[10 11]
  [13 14]]

 [[19 20]
  [22 23]]]


In [64]:
# Задача № 42
# Выход: выберите второй столбец для каждой строки в каждой матрице

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код

result = tensor[:, :, 1]
print(f'Второй столбец для каждой строки в каждой матрице:\n{result}')

Второй столбец для каждой строки в каждой матрице:
[[ 2  5  8]
 [11 14 17]
 [20 23 26]]


In [65]:
# Задача № 43
# Выход: выберите все элементы второй строки для каждой матрицы

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код

result = tensor[:, 1, :]
print(f'Все элементы вдоль второго измерения для каждой матрицы:\n{result}')

Все элементы вдоль второго измерения для каждой матрицы:
[[ 4  5  6]
 [13 14 15]
 [22 23 24]]


In [66]:
# Задача № 44
# Выход: выберите элементы в каждой матрице в нижнем правом углу, начиная с третьей строки
# и третьего столбца и до конца каждой матрицы. Обратите внимание - результат должен быть 
# трехмерным массивом, где каждая подматрица содержит элементы в нижнем правом углу соответствующей матрицы

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код

result = tensor[0:3, 2:, 2:]
print(f'Элементы в каждой матрице в нижнем правом угле:\n{result}')

Элементы в каждой матрице в нижнем правом угле:
[[[ 9]]

 [[18]]

 [[27]]]


In [67]:
# Задача № 45
# Выход: выберите четные строки и четные столбцы в каждой матрице

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]], 

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код

result = tensor[0:3, 1::2, 1::2]
print(f'Четные строки и четные столбцы в каждой матрице:\n{result}')

Четные строки и четные столбцы в каждой матрице:
[[[ 5]]

 [[14]]

 [[23]]]


In [4]:
# Задача № 46
# Выход: выберите из массива arr все элементы, которые больше 3

arr = np.array([1, 2, 3, 4, 5, 6])

# ваш код

result = arr[arr > 3]
print(result)

[4 5 6]


In [5]:
# Задача № 47
# Выход: выберите из массива arr все четные числа

arr = np.array([1, 2, 3, 4, 5, 6])

# ваш код

result = arr[arr%2==0]
print(result)

[2 4 6]


In [6]:
# Задача № 48
# Выход: выберите из 2D массива matrix все элементы, которые больше 5

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# ваш код

result = matrix[matrix > 5]
print(result)

[6 7 8 9]


In [7]:
# Задача № 49
# Выход: инвертируйте булев массив arr

arr = np.array([True, False, True, False])

# ваш код

arr = list((False if elem==True else True for elem in arr))
result = np.array(arr) 
print(result)

[False  True False  True]


In [8]:
# Задача № 50
# Выход: выберите из массива arr все числа больше 2 и меньше 6

arr = np.array([1, 2, 3, 4, 5, 6])

# ваш код

result = arr[(arr>2) & (arr<6)]
print(result)

[3 4 5]


In [9]:
# Задача № 51
# Выход: выберите из 2D массива matrix все строки, в которых есть хотя бы одно число больше 7

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# ваш код

result = matrix[np.any(matrix>7, axis=1)]
print(result)

[[7 8 9]]


In [10]:
# Задача № 52
# Выход: покажите из массива arr все числа больше и равные 4

arr = np.array([1, 2, 3, 4, 5, 6])

# ваш код

result = arr[(arr==4) | (arr>4)]
print(result)

[4 5 6]


In [11]:
# Задача № 53
# Выход: замените в массиве arr все четные числа на 0

arr = np.array([1, 2, 3, 4, 5, 6])

# ваш код

arr[arr%2==0] = 0
print(arr)

[1 0 3 0 5 0]


In [12]:
# Задача № 54
# Выход: выберите из массива arr только те элементы,
# для которых соответствующее значение в массиве index_array равно True

arr = np.array([1, 2, 3, 4, 5, 6])
index_array = np.array([True, False, True, False, True, False])

# ваш код

result = arr[index_array==True]
print(result)

[1 3 5]


In [13]:
# Задача № 55
# Выход: выберите из 2D массива matrix все элементы, которые делятся на 3

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# ваш код

result = matrix[matrix%3==0]
print(result)

[3 6 9]


In [14]:
# Задача № 56
# Выход: проверить, содержит ли массив хотя бы одно положительное число и
# все ли элементы отрицательны. Необходимо проверить это с помощью функции check_array

array2 = np.array([-2, -4, -6, 8, -1])

# ваш код

def check_array(arr):
    has_positive = np.any(arr>0)
    all_negative = np.all(arr<0)

    return has_positive, all_negative

result = check_array(array2) # проверь массив array2 с помощью функции check_array

print(f"В массиве есть хотя бы одно положительное число: {result[0]}")
print(f"Все элементы массива отрицательны: {result[1]}")

В массиве есть хотя бы одно положительное число: True
Все элементы массива отрицательны: False


In [15]:
# Задача № 57
# Дано: набор данных о продажах товаров, представленный в виде двумерного массива sales_data_array.
#       Каждая строка представляет собой информацию о продажах для конкретного товара, а столбцы содержат
#       следующую информацию: номер товара, количество проданных единиц, и доход от продаж.
# Выход: 1. Есть ли хотя бы одна запись с нулевыми продажами (количество проданных единиц равно 0)?
#        2. Все ли товары имеют положительный доход от продаж?

sales_data_array = np.array([[1, 10, 100],
                             [2, 5, 50],
                             [3, 0, 0],
                             [4, 8, 80]])

# ваш код

def analyze_sales_data(sales_data):
    has_zero_sales = np.any(sales_data==0)
    all_positive_income = np.all(sales_data>0)

    return has_zero_sales, all_positive_income

result = analyze_sales_data(sales_data_array)

print(f"Есть ли товары с нулевыми продажами: {result[0]}")
print(f"Все ли товары имеют положительный доход: {result[1]}")

Есть ли товары с нулевыми продажами: True
Все ли товары имеют положительный доход: False


In [16]:
# Задача № 58
# Дано: массив data размером 5 x 5, заполненный случайными целыми числами от 0 до 9
# Выход: Замените все четные числа в массиве на 0, а все нечетные на 1.
#        Используйте булеву индексацию для создания масок, которые соответствуют этим условиям,
#        и примените их к массиву data.  

data = np.array([[6, 4, 8, 7, 9],
                 [0, 0, 1, 7, 2],
                 [5, 7, 9, 0, 4],
                 [5, 1, 2, 8, 6],
                 [9, 8, 3, 0, 3]])

# ваш код

even_mask = data%2==0
odd_mask = data%2!=0

data[even_mask] = 0
data[odd_mask] = 1
print(data)

[[0 0 0 1 1]
 [0 0 1 1 0]
 [1 1 1 0 0]
 [1 1 0 0 0]
 [1 0 1 0 1]]


In [17]:
# Задача № 59
# Дано: массив data размером 6 x 6, заполненный случайными целыми числами от 0 до 9
# Выход: Найдите среднее арифметическое всех элементов, которые находятся на главной
#        диагонали массива. Используйте булеву индексацию для создания маски, которая
#        соответствует этому условию, и примените ее к массиву data.

data = np.array([[8, 3, 9, 1, 9, 0],
                 [5, 4, 2, 7, 4, 2],
                 [0, 8, 7, 4, 3, 9],
                 [0, 9, 7, 1, 0, 1],
                 [7, 1, 0, 3, 9, 3],
                 [5, 8, 0, 4, 0, 6]])

# ваш код

mask = data[np.eye(6)==1]
mean = mask.mean()
print(f'Среднее арифметическое элементов на диагоналях: {mean:.2f}')

Среднее арифметическое элементов на диагоналях: 5.83


In [18]:
# Задача № 60
# Дано: массив data, содержащий информацию о студентах: имя, возраст, пол, курс и средний балл
# Выход: Найдите имена, средние баллы и другую информацию студентов, которые старше 20 лет,
#        женского пола и учатся на третьем курсе. Используйте булеву индексацию для создания
#        маски, которая соответствует этому условию, и примените ее к массиву data.  

data = np.array([
    ['Анна', 19, 'F', 1, 4.5],
    ['Борис', 21, 'M', 2, 3.7],
    ['Вера', 21, 'F', 3, 4.8],
    ['Глеб', 22, 'M', 4, 3.9],
    ['Дарья', 18, 'F', 1, 4.2],
    ['Егор', 23, 'M', 3, 4.1],
    ['Жанна', 21, 'F', 2, 4.6],
    ['Захар', 19, 'M', 1, 4.0]
])

# ваш код

mask = data[(data[:, 1].astype(int)>20) & (data[:, 2]=='F') & (data[:, 3].astype(int)==3)]
result = mask
print(result)

[['Вера' '21' 'F' '3' '4.8']]


In [19]:
# Задача № 61
# Выход: транспонируйте массив и сохраните результат в переменной transposed_arr

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15]])

# ваш код

transposed_arr = arr.T
print("Транспонированный массив:")
print(transposed_arr)

Транспонированный массив:
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [ ]:
# Задача № 62
# Выход: умножьте две матрицы arr1 и arr2, затем выведите результат

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

# ваш код

result = arr1.dot(arr2)
print("Результат умножения:")
print(result)

Результат умножения:
[[19 22]
 [43 50]]


In [ ]:
# Задача № 63
# Выход: измените форму массива arr размером 4x3 на (2, 6)

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])

# ваш код

reshaped_arr = arr.reshape((2, 6))
print("Массив после изменения формы:")
print(reshaped_arr)

Массив после изменения формы:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [22]:
# Задача № 64
# Выход: поменяйте местами оси массива

data = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10]])

# ваш код

data_new = np.swapaxes(data, 0, 1)
print("Изначальные данные:")
print(data)
print("Данные после перестановки:")
print(data_new)

Изначальные данные:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Данные после перестановки:
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [23]:
# Задача № 65
# Выход: создайте массив размером 2x8, заполненный значениями от 0 до 15

# ваш код

arr = np.reshape(np.arange(0, 16), (2, 8))
print("Массив:")
print(arr)

Массив:
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [24]:
# Задача № 66
# Выход: умножьте две матрицы arr1 и arr2, затем транспонируйте результат

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

# ваш код

result = (arr1 @ arr2)
transposed_result = result.transpose()
print("Транспонированный результат умножения:")
print(transposed_result)

Транспонированный результат умножения:
[[19 43]
 [22 50]]


In [27]:
# Задача № 67
# Выход: сохраните в переменной A транспонированный верхний левый квадрант:
# [[1 2]
#  [5 6]]

A = np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]])

# ваш код

A = A[:2, :2].T
print(A)

[[1 5]
 [2 6]]


In [28]:
# Задача № 68
# Выход: транспонировать только те строки, у которых первый элемент больше 3

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]])

# ваш код

condition = A[:, 0]>3
A[condition] = A[condition].T 
print("Матрица A после транспонирования строк с первым элементом больше 3:")
print(A)

Матрица A после транспонирования строк с первым элементом больше 3:
[[ 1  2  3  4]
 [ 5  9 13 17]
 [ 6 10 14 18]
 [ 7 11 15 19]
 [ 8 12 16 20]]
