Варианты решения задач

In [2]:
import numpy as np

In [5]:
# Задача № 1 
# Выход: Создайте одномерный массив из 5 целых чисел от 0 до 4

# ваш код

array = np.linspace(0, 4, 5, dtype=int)
print(array)

[0 1 2 3 4]


In [6]:
# Задача № 2
# Выход: Создайте двумерный массив размером 4x5, заполненный нулями

# ваш код

array = np.zeros((4, 5))
print(array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
# Задача № 3
# Выход: Создайте массив размером 3x2, заполненный единицами

# ваш код

array = np.ones((3, 2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Задача № 4
# Выход: Создайте одномерный массив из четных чисел от 0 до 8 (включительно) с шагом 2

# ваш код

array = np.arange(0, 9, 2)
print(array)

[0 2 4 6 8]


In [9]:
# Задача № 5
# Выход: Создайте массив из 5 равномерно распределенных значений между 0 и 1, включая обе границы

# ваш код

array = np.linspace(0, 1, num=5, endpoint=True)
print(array)

[0.   0.25 0.5  0.75 1.  ]


In [10]:
# Задача № 6
# Выход: Создайте массив размером 2x3, заполненного значением 7

# ваш код

array =  np.full((2, 3), 7)
print(array)

[[7 7 7]
 [7 7 7]]


In [11]:
# Задача № 7
# Выход: Создайте массив из 5 строк и 2 столбцов, содержащий только булевы значения True

# ваш код

array = np.full((5, 2), True)
print(array)

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


In [19]:
# Задача № 8
# Выход: Создайте трехмерный массив (каждый массив должен содержать две строки и четыре столбца) и определите его количество измерений

# ваш код

arr = np.zeros((3, 2, 4)) 
dimensions = arr.ndim 
print(arr, "\n")
print("Количество измерений:", dimensions)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]] 

Количество измерений: 3


In [21]:
# Задача № 9
# Выход: Создайте матрицу 3x4 заполненную единицами и определите её размеры

# ваш код

matrix = np.ones((3, 4)) 
matrix_shape = matrix.shape
print("Матрица:")
print(matrix, "\n")
print("Размеры матрицы:", matrix_shape)

Матрица:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

Размеры матрицы: (3, 4)


In [23]:
# Задача № 10
# Выход: Создайте квадратную матрицу 4x4 с единицами на главной диагонали

# ваш код

identity_matrix = np.identity(4)
print("Квадратная матрица:")
print(identity_matrix)

Квадратная матрица:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Задача № 11
# Выход: Повторите созданный массив с элементами (1, 2, 3) 3 раза, чтобы получить в итоге такой массив

# ваш код

original_array = np.array([1, 2, 3])
tiled_array = np.tile(original_array, (3, 1))
print("Исходный массив:")
print(original_array, "\n")
print("Массив с повторенными элементами:")
print(tiled_array)

Исходный массив:
[1 2 3] 

Массив с повторенными элементами:
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# Задача № 12
# Выход: Повторите созданный массив с элементами (1, 2, 3) 4 раза вдоль оси 0 (строки)
# и дополнительно, каждую строку массива увеличьте по размеру в два раза с те же элементами (вдоль оси 1(столбцы))

# ваш код

original_array = np.array([1, 2, 3])
tiled_array =  np.tile(original_array, (4, 2))
print("Исходный массив:")
print(original_array, '\n')
print("Массив с повторенными элементами:")
print(tiled_array)

Исходный массив:
[1 2 3] 

Массив с повторенными элементами:
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]


In [ ]:
# Задача № 13
# Выход: Повторите созданный массив с элементами (1, 2, 3) 4 раза вдоль оси 0 (строки)
# и дополнительно, каждую строку массива увеличьте по размеру в два раза с те же
# элементами (вдоль оси 1 (столбцы)), и еще, дополнительно, сделайте этот массив двумерным

# ваш код

original_array = np.array([1, 2, 3])
tiled_array = np.tile(original_array, (2, 4, 2))
print("Исходный массив:")
print(original_array, '\n')
print("Массив с повторенными элементами:")
print(tiled_array)

Исходный массив:
[1 2 3] 

Массив с повторенными элементами:
[[[1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]]

 [[1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]]]


In [ ]:
# Задача № 14
# Дано: У вас есть массив arr с целыми числами.
# Выход: Напишите программу для определения текущего типа данных элементов массива

# ваш код

current_dtype = arr.dtype
print("Исходный массив:", arr)
print("Текущий тип данных:", current_dtype)

Исходный массив: [1 2 3 4]
Текущий тип данных: int32


In [30]:
# Задача № 15
# Выход: создать массив arr с числами от 1 до 3, включительно, и указать явно тип данных целых чисел

# ваш код

arr = np.arange(1, 4, dtype=int) 
print("Массив целых чисел:", arr)
print("Тип данных:", arr.dtype)

Массив целых чисел: [1 2 3]
Тип данных: int32


In [ ]:
# Задача № 16
# Дано: массив arr_float с вещественными числами 
# Выход: напишите программу для создания нового массива arr_int, в котором вещественные числа будут округлены до целых

arr_float = np.array([1.2, 2.5, 3.8, 4.1])

# ваш код

arr_int = arr_float.astype(int)
print("Исходный массив:", arr_float)
print("Тип данных:", arr_float.dtype, '\n')
print("Массив округленных целых чисел:", arr_int)
print("Тип данных:", arr_int.dtype)

Исходный массив: [1.2 2.5 3.8 4.1]
Тип данных: float64 

Массив округленных целых чисел: [1 2 3 4]
Тип данных: int32


In [50]:
# Задача № 17
# Дано: два датасета с данными о температуре и влажности. Каждый датасет представлен в виде двумерного массива,
# где строки представляют дни, а столбцы представляют конкретные моменты времени в течение дня. Тип данных - int. Вам нужно изменить их на float.
# Выход: 1. Создайте функцию, которая принимает на вход два аргумента: dataset и new_dtype.
#        2. Используйте функцию для изменения типа данных каждого датасета на тип float.

# Датасет температуры (тип данных: int)
temp_data = np.array([[22, 25, 24, 23, 21],
                      [20, 18, 19, 22, 24]])

# Датасет влажности (тип данных: int)
humid_data = np.array([[45, 50, 48, 52, 47],
                       [45, 48, 50, 51, 53]])

# ваш код


def change_data_type(dataset, new_dtype):
    return dataset.astype(new_dtype) 

temp_data = change_data_type(temp_data, float)
humid_data = change_data_type(humid_data, float)

print(f'Новый тип данных temp_data: {temp_data.dtype}')
print(f'Новый тип данных humid_data: {humid_data.dtype}')

Новый тип данных temp_data: float64
Новый тип данных humid_data: float64


In [36]:
# Задача № 18
# Выход: Выполните поэлементное сложение двух массивов arr1 и arr2 и выведите результат на экран

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[3, 2, 1]])

# ваш код

result_add = arr1 + arr2
print(result_add)

[[4 4 4]]


In [37]:
# Задача № 19
# Выход: Выполните поэлементное умножение двух массивов arr1 и arr2 и выведите результат на экран

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

# ваш код

result_multiply = arr1 * arr2
print(result_multiply)

[[ 7 16 27]
 [40 55 72]]


In [38]:
# Задача № 20
# Выход: Выполните поэлементное деление массива на 2 и сохраните результат в result_divide

arr1 = np.array([[8, 8, 4], 
                 [4, 2, 2], 
                 [10, 10, 2]])

# ваш код

result_divide = arr1 / 2
print(result_divide)

[[4. 4. 2.]
 [2. 1. 1.]
 [5. 5. 1.]]


In [39]:
# Задача № 21
# Выход: Выполните поэлементное сложение двух массивов и сохраните результат в массив result_add

arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])

arr2 = np.array([[9, 8, 7], 
                 [6, 5, 4], 
                 [3, 2, 1]])

# ваш код

result_add = arr1 + arr2
print(result_add)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [40]:
# Задача № 22
# Выход: Выполните поэлементное вычитание arr1 из arr2 и сохраните результат в массив result_subtract

arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])

arr2 = np.array([[10, 11, 12], 
                 [13, 14, 15], 
                 [16, 17, 18]])

# ваш код

result_subtract = arr1 - arr2
print(result_subtract)

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [41]:
# Задача № 23
# Выход: Возведите все элементы массива в квадрат и сохраните результат в result_double

arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])

# ваш код

result_double = arr1 ** 2
print(result_double)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [42]:
# Задача № 24
# Дано: массив grades из оценок студентов (от 0 до 100).
# Выход: Преобразуйте тип данных массива grades на float, затем напишите код, который увеличит все оценки более 50 на 10%

grades = np.array([75, 45, 60, 90, 30, 85, 40])

# ваш код

grades = grades.astype(float)
grades = np.where(grades>50, grades*1.1, grades)
print(grades)

[82.5 45.  66.  99.  30.  93.5 40. ]


In [ ]:
# Задача № 25
# Выход: Выполните умножение вектора (vector) на скаляр (scalar)

vector = np.array([1, 2, 3, 4])
scalar = 2

# ваш код

result = vector * scalar
print(result)

[2 4 6 8]


In [44]:
# Задача № 26
# Дано: массив prices из цен на товары
# Выход: напишите код, который уменьшит цены на 10% для товаров с ценой выше 40

prices = np.array([50, 30, 70, 40, 90], float)

# ваш код

prices = np.where(prices>40, prices*0.9, prices)
print(prices)

[45. 30. 63. 40. 81.]


In [45]:
# Задача № 27
# Выход: выполните сложение матрицы и вектора

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

vector = np.array([0, 1, 2])

# ваш код

result = matrix + vector
print(result)

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [46]:
# Задача № 28
# Выход: выполните умножение матриц matrix_a и matrix_b. Создайте matrix_b с такими значениями, чтобы получить в итоге умножения такую матрицу:
# [[ 10  20  30]
# [ 80 100 120]
# [210 240 270]]

matrix_a = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])

# ваш код

matrix_b = [[10], [20], [30]]
result = matrix_a * matrix_b
print(result)

[[ 10  20  30]
 [ 80 100 120]
 [210 240 270]]


In [47]:
# Задача № 29
# Выход: выполните вычитание матриц matrix_c и matrix_d. Создайте matrix_d с такими значениями, чтобы получить в итоге вычитания такую матрицу:
# [[ 9 18 27]
# [39 48 57]
# [69 78 87]]

matrix_c = np.array([[10, 20, 30], 
                     [40, 50, 60], 
                     [70, 80, 90]])

# ваш код

matrix_d = [1, 2, 3]
result = matrix_c - matrix_d
print(result)

[[ 9 18 27]
 [39 48 57]
 [69 78 87]]


In [48]:
# Задача № 30
# Выход: выполните умножение матриц matrix_e и matrix_f. Создайте matrix_f с такими значениями, чтобы получить в итоге умножения такую матрицу:
# [[ 2 8]
# [18 32]]

matrix_e = np.array([[2, 4], 
                     [6, 8]])

# ваш код

matrix_f = [[1, 2], [3, 4]]
result = matrix_e * matrix_f
print(result)

[[ 2  8]
 [18 32]]


In [52]:
# Задача № 31
# Выход: выведите первый и последний элементы с помощью срезов

arr = np.array([1, 2, 3, 4, 5])

# ваш код

arr1 = arr[0]
arr2 = arr[-1]
print(f'Первый элемент: {arr1}')  
print(f'Последний элемент: {arr2}')

Первый элемент: 1
Последний элемент: 5


In [53]:
# Задача № 32
# Выход: выведите вторую строку и третий столбец с помощью срезов

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

# ваш код

arr1 = arr[1, :] 
arr2 = arr[:, 2]
print(f'Вторая строка: {arr1}')  
print(f'Третий столбец: {arr2}')

Вторая строка: [4 5 6]
Третий столбец: [3 6 9]


In [54]:
# Задача № 33
# Выход: выведите первый слой, вторую строку и первый столбец с помощью срезов

arr = np.array([[[1, 2], 
                 [3, 4]], 
                [[5, 6], 
                 [7, 8]], 
                [[9, 10], 
                 [11, 12]]])

# ваш код

arr1 = arr[0, :, :]
arr2 = arr[0, 1, :]
arr3 = arr[0, :, 0]
print(f'Первый слой:\n{arr1}')  
print(f'Вторая строка первого слоя: {arr2}')  
print(f'Первый столбец первого слоя: {arr3}')

Первый слой:
[[1 2]
 [3 4]]
Вторая строка первого слоя: [3 4]
Первый столбец первого слоя: [1 3]


In [55]:
# Задача № 34
# Выход: выведите все элементы в четных столбцах

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# ваш код

arr1 = arr[:, 1::2]
print(f'Элементы с четными столбцами:\n{arr1}')

Элементы с четными столбцами:
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [56]:
# Задача № 35
# Выход: выведите все элементы в нечетных столбцах

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# ваш код

arr1 = arr[:, ::2]
print(f'Элементы с нечетными столбцами:\n{arr1}')

Элементы с нечетными столбцами:
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [57]:
# Задача № 36
# Выход: выведите все элементы с нечетными строками

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# ваш код

arr1 = arr[::2, :]
print(f'Элементы с нечетными строками:\n{arr1}')

Элементы с нечетными строками:
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [58]:
# Задача № 37
# Выход: выделите подматрицу, состоящую из трех последних строк и двух первых столбцов

matrix = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25]])

# ваш код

submatrix = matrix[-3:, :2]
print(f'Матрица трех последних строк и двух первых столбцов:\n{submatrix}')

Матрица трех последних строк и двух первых столбцов:
[[11 12]
 [16 17]
 [21 22]]


In [59]:
# Задача № 38
# Выход: выделите подматрицу, состоящую из второй и третьей строк, а также третьего и четвёртого столбцов

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

# ваш код

submatrix = matrix[1:3, 2:]
print(f'Матрица из второй и третьей строк, а также третьего и четвёртого столбцов:\n{submatrix}')

Матрица из второй и третьей строк, а также третьего и четвёртого столбцов:
[[ 7  8]
 [11 12]]


In [61]:
# Задача № 39
# Выход: выведите подматрицу, состоящую из элементов с индексами от 1 до 2 по обеим осям, с помощью срезов

arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12], 
                [13, 14, 15, 16]])

# ваш код

submatrix = arr[1:3, 1:3]
print(f'Подматрица, состоящая из элементов с индексами от 1 до 2 по обеим осям:\n{submatrix}')

Подматрица, состоящая из элементов с индексами от 1 до 2 по обеим осям:
[[ 6  7]
 [10 11]]


In [62]:
# Задача № 40
# Выход: выведите элементы в обратном порядке с шагом 2 с помощью срезов

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# ваш код

submatrix = arr[::-2]
print(f'Элементы в обратном порядке с шагом 2:\n{submatrix}')

Элементы в обратном порядке с шагом 2:
[10  8  6  4  2]


In [63]:
# Задача № 41
# Выход: выберите подматрицу 2x2 в верхнем левом углу для каждой матрицы

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код

result = tensor[:, :2, :2]
print(f'Подматрица 2x2 в верхнем левом углу для каждой матрицы:\n{result}')

Подматрица 2x2 в верхнем левом углу для каждой матрицы:
[[[ 1  2]
  [ 4  5]]

 [[10 11]
  [13 14]]

 [[19 20]
  [22 23]]]


In [64]:
# Задача № 42
# Выход: выберите второй столбец для каждой строки в каждой матрице

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код

result = tensor[:, :, 1]
print(f'Второй столбец для каждой строки в каждой матрице:\n{result}')

Второй столбец для каждой строки в каждой матрице:
[[ 2  5  8]
 [11 14 17]
 [20 23 26]]


In [65]:
# Задача № 43
# Выход: выберите все элементы второй строки для каждой матрицы

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код

result = tensor[:, 1, :]
print(f'Все элементы вдоль второго измерения для каждой матрицы:\n{result}')

Все элементы вдоль второго измерения для каждой матрицы:
[[ 4  5  6]
 [13 14 15]
 [22 23 24]]


In [66]:
# Задача № 44
# Выход: выберите элементы в каждой матрице в нижнем правом углу, начиная с третьей строки
# и третьего столбца и до конца каждой матрицы. Обратите внимание - результат должен быть 
# трехмерным массивом, где каждая подматрица содержит элементы в нижнем правом углу соответствующей матрицы

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код

result = tensor[0:3, 2:, 2:]
print(f'Элементы в каждой матрице в нижнем правом угле:\n{result}')

Элементы в каждой матрице в нижнем правом угле:
[[[ 9]]

 [[18]]

 [[27]]]


In [67]:
# Задача № 45
# Выход: выберите четные строки и четные столбцы в каждой матрице

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]], 

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код

result = tensor[0:3, 1::2, 1::2]
print(f'Четные строки и четные столбцы в каждой матрице:\n{result}')

Четные строки и четные столбцы в каждой матрице:
[[[ 5]]

 [[14]]

 [[23]]]
