Варианты решения задач

In [1]:
import numpy as np

In [5]:
# Задача № 1 
# Выход: Создайте одномерный массив из 5 целых чисел от 0 до 4

# ваш код

array = np.linspace(0, 4, 5, dtype=int)
print(array)

[0 1 2 3 4]


In [6]:
# Задача № 2
# Выход: Создайте двумерный массив размером 4x5, заполненный нулями

# ваш код

array = np.zeros((4, 5))
print(array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
# Задача № 3
# Выход: Создайте массив размером 3x2, заполненный единицами

# ваш код

array = np.ones((3, 2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Задача № 4
# Выход: Создайте одномерный массив из четных чисел от 0 до 8 (включительно) с шагом 2

# ваш код

array = np.arange(0, 9, 2)
print(array)

[0 2 4 6 8]


In [9]:
# Задача № 5
# Выход: Создайте массив из 5 равномерно распределенных значений между 0 и 1, включая обе границы

# ваш код

array = np.linspace(0, 1, num=5, endpoint=True)
print(array)

[0.   0.25 0.5  0.75 1.  ]


In [10]:
# Задача № 6
# Выход: Создайте массив размером 2x3, заполненного значением 7

# ваш код

array =  np.full((2, 3), 7)
print(array)

[[7 7 7]
 [7 7 7]]


In [11]:
# Задача № 7
# Выход: Создайте массив из 5 строк и 2 столбцов, содержащий только булевы значения True

# ваш код

array = np.full((5, 2), True)
print(array)

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


In [29]:
# Задача № 8
# Выход: Создайте трехмерный массив (каждый массив должен содержать две строки и
#        четыре столбца) и определите его количество измерений

# ваш код

arr = np.zeros((3, 2, 4)) 
dimensions = arr.ndim 
print(arr, "\n")
print("Количество измерений:", dimensions)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]] 

Количество измерений: 3


In [21]:
# Задача № 9
# Выход: Создайте матрицу 3x4 заполненную единицами и определите её размеры

# ваш код

matrix = np.ones((3, 4)) 
matrix_shape = matrix.shape
print("Матрица:")
print(matrix, "\n")
print("Размеры матрицы:", matrix_shape)

Матрица:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

Размеры матрицы: (3, 4)


In [23]:
# Задача № 10
# Выход: Создайте квадратную матрицу 4x4 с единицами на главной диагонали

# ваш код

identity_matrix = np.identity(4)
print("Квадратная матрица:")
print(identity_matrix)

Квадратная матрица:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Задача № 11
# Выход: Повторите созданный массив с элементами (1, 2, 3) 3 раза, чтобы получить в итоге такой массив

# ваш код

original_array = np.array([1, 2, 3])
tiled_array = np.tile(original_array, (3, 1))
print("Исходный массив:")
print(original_array, "\n")
print("Массив с повторенными элементами:")
print(tiled_array)

Исходный массив:
[1 2 3] 

Массив с повторенными элементами:
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# Задача № 12
# Выход: Повторите созданный массив с элементами (1, 2, 3) 4 раза вдоль оси 0 (строки)
#        и дополнительно, каждую строку массива увеличьте по размеру в два раза с те же элементами
#        (вдоль оси 1(столбцы))

# ваш код

original_array = np.array([1, 2, 3])
tiled_array =  np.tile(original_array, (4, 2))
print("Исходный массив:")
print(original_array, '\n')
print("Массив с повторенными элементами:")
print(tiled_array)

Исходный массив:
[1 2 3] 

Массив с повторенными элементами:
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]


In [ ]:
# Задача № 13
# Выход: Повторите созданный массив с элементами (1, 2, 3) 4 раза вдоль оси 0 (строки)
# и дополнительно, каждую строку массива увеличьте по размеру в два раза с те же
# элементами (вдоль оси 1 (столбцы)), и еще, дополнительно, сделайте этот массив двумерным

# ваш код

original_array = np.array([1, 2, 3])
tiled_array = np.tile(original_array, (2, 4, 2))
print("Исходный массив:")
print(original_array, '\n')
print("Массив с повторенными элементами:")
print(tiled_array)

Исходный массив:
[1 2 3] 

Массив с повторенными элементами:
[[[1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]]

 [[1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]
  [1 2 3 1 2 3]]]


In [ ]:
# Задача № 14
# Дано: У вас есть массив arr с целыми числами.
# Выход: Напишите программу для определения текущего типа данных элементов массива

# ваш код

current_dtype = arr.dtype
print("Исходный массив:", arr)
print("Текущий тип данных:", current_dtype)

Исходный массив: [1 2 3 4]
Текущий тип данных: int32


In [30]:
# Задача № 15
# Выход: создать массив arr с числами от 1 до 3, включительно, и указать явно тип данных целых чисел

# ваш код

arr = np.arange(1, 4, dtype=int) 
print("Массив целых чисел:", arr)
print("Тип данных:", arr.dtype)

Массив целых чисел: [1 2 3]
Тип данных: int32


In [ ]:
# Задача № 16
# Дано: массив arr_float с вещественными числами 
# Выход: напишите программу для создания нового массива arr_int, в котором вещественные числа будут округлены до целых

arr_float = np.array([1.2, 2.5, 3.8, 4.1])

# ваш код

arr_int = arr_float.astype(int)
print("Исходный массив:", arr_float)
print("Тип данных:", arr_float.dtype, '\n')
print("Массив округленных целых чисел:", arr_int)
print("Тип данных:", arr_int.dtype)

Исходный массив: [1.2 2.5 3.8 4.1]
Тип данных: float64 

Массив округленных целых чисел: [1 2 3 4]
Тип данных: int32


In [30]:
# Задача № 17
# Дано: два датасета с данными о температуре и влажности. Каждый датасет представлен в виде двумерного массива,
#       где строки представляют дни, а столбцы представляют конкретные моменты времени в течение дня.
#       Тип данных - int. Вам нужно изменить их на float.
# Выход: 1. Создайте функцию, которая принимает на вход два аргумента: dataset и new_dtype.
#        2. Используйте функцию для изменения типа данных каждого датасета на тип float.

# Датасет температуры (тип данных: int)
temp_data = np.array([[22, 25, 24, 23, 21],
                      [20, 18, 19, 22, 24]])

# Датасет влажности (тип данных: int)
humid_data = np.array([[45, 50, 48, 52, 47],
                       [45, 48, 50, 51, 53]])

# ваш код


def change_data_type(dataset, new_dtype):
    return dataset.astype(new_dtype) 

temp_data = change_data_type(temp_data, float)
humid_data = change_data_type(humid_data, float)

print(f'Новый тип данных temp_data: {temp_data.dtype}')
print(f'Новый тип данных humid_data: {humid_data.dtype}')

Новый тип данных temp_data: float64
Новый тип данных humid_data: float64


In [36]:
# Задача № 18
# Выход: Выполните поэлементное сложение двух массивов arr1 и arr2 и выведите результат на экран

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[3, 2, 1]])

# ваш код

result_add = arr1 + arr2
print(result_add)

[[4 4 4]]


In [37]:
# Задача № 19
# Выход: Выполните поэлементное умножение двух массивов arr1 и arr2 и выведите результат на экран

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

# ваш код

result_multiply = arr1 * arr2
print(result_multiply)

[[ 7 16 27]
 [40 55 72]]


In [38]:
# Задача № 20
# Выход: Выполните поэлементное деление массива на 2 и сохраните результат в result_divide

arr1 = np.array([[8, 8, 4], 
                 [4, 2, 2], 
                 [10, 10, 2]])

# ваш код

result_divide = arr1 / 2
print(result_divide)

[[4. 4. 2.]
 [2. 1. 1.]
 [5. 5. 1.]]


In [39]:
# Задача № 21
# Выход: Выполните поэлементное сложение двух массивов и сохраните результат в массив result_add

arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])

arr2 = np.array([[9, 8, 7], 
                 [6, 5, 4], 
                 [3, 2, 1]])

# ваш код

result_add = arr1 + arr2
print(result_add)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [40]:
# Задача № 22
# Выход: Выполните поэлементное вычитание arr1 из arr2 и сохраните результат в массив result_subtract

arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])

arr2 = np.array([[10, 11, 12], 
                 [13, 14, 15], 
                 [16, 17, 18]])

# ваш код

result_subtract = arr1 - arr2
print(result_subtract)

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [41]:
# Задача № 23
# Выход: Возведите все элементы массива в квадрат и сохраните результат в result_double

arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]])

# ваш код

result_double = arr1 ** 2
print(result_double)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [42]:
# Задача № 24
# Дано: массив grades из оценок студентов (от 0 до 100).
# Выход: Преобразуйте тип данных массива grades на float, затем напишите код, который увеличит все оценки более 50 на 10%

grades = np.array([75, 45, 60, 90, 30, 85, 40])

# ваш код

grades = grades.astype(float)
grades = np.where(grades>50, grades*1.1, grades)
print(grades)

[82.5 45.  66.  99.  30.  93.5 40. ]


In [ ]:
# Задача № 25
# Выход: Выполните умножение вектора (vector) на скаляр (scalar)

vector = np.array([1, 2, 3, 4])
scalar = 2

# ваш код

result = vector * scalar
print(result)

[2 4 6 8]


In [44]:
# Задача № 26
# Дано: массив prices из цен на товары
# Выход: напишите код, который уменьшит цены на 10% для товаров с ценой выше 40

prices = np.array([50, 30, 70, 40, 90], float)

# ваш код

prices = np.where(prices>40, prices*0.9, prices)
print(prices)

[45. 30. 63. 40. 81.]


In [45]:
# Задача № 27
# Выход: выполните сложение матрицы и вектора

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

vector = np.array([0, 1, 2])

# ваш код

result = matrix + vector
print(result)

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [31]:
# Задача № 28
# Выход: выполните умножение матриц matrix_a и matrix_b. Создайте matrix_b с такими значениями,
#        чтобы получить в итоге умножения такую матрицу:
# [[ 10  20  30]
# [ 80 100 120]
# [210 240 270]]

matrix_a = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])

# ваш код

matrix_b = [[10], [20], [30]]
result = matrix_a * matrix_b
print(result)

[[ 10  20  30]
 [ 80 100 120]
 [210 240 270]]


In [ ]:
# Задача № 29
# Выход: выполните вычитание матриц matrix_c и matrix_d.
#        Создайте matrix_d с такими значениями, чтобы получить в итоге вычитания такую матрицу:
# [[ 9 18 27]
# [39 48 57]
# [69 78 87]]

matrix_c = np.array([[10, 20, 30], 
                     [40, 50, 60], 
                     [70, 80, 90]])

# ваш код

matrix_d = [1, 2, 3]
result = matrix_c - matrix_d
print(result)

[[ 9 18 27]
 [39 48 57]
 [69 78 87]]


In [ ]:
# Задача № 30
# Выход: выполните умножение матриц matrix_e и matrix_f. Создайте matrix_f с такими значениями,
#        чтобы получить в итоге умножения такую матрицу:
# [[ 2 8]
# [18 32]]

matrix_e = np.array([[2, 4], 
                     [6, 8]])

# ваш код

matrix_f = [[1, 2], [3, 4]]
result = matrix_e * matrix_f
print(result)

[[ 2  8]
 [18 32]]


In [52]:
# Задача № 31
# Выход: выведите первый и последний элементы с помощью срезов

arr = np.array([1, 2, 3, 4, 5])

# ваш код

arr1 = arr[0]
arr2 = arr[-1]
print(f'Первый элемент: {arr1}')  
print(f'Последний элемент: {arr2}')

Первый элемент: 1
Последний элемент: 5


In [53]:
# Задача № 32
# Выход: выведите вторую строку и третий столбец с помощью срезов

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

# ваш код

arr1 = arr[1, :] 
arr2 = arr[:, 2]
print(f'Вторая строка: {arr1}')  
print(f'Третий столбец: {arr2}')

Вторая строка: [4 5 6]
Третий столбец: [3 6 9]


In [54]:
# Задача № 33
# Выход: выведите первый слой, вторую строку и первый столбец с помощью срезов

arr = np.array([[[1, 2], 
                 [3, 4]], 
                [[5, 6], 
                 [7, 8]], 
                [[9, 10], 
                 [11, 12]]])

# ваш код

arr1 = arr[0, :, :]
arr2 = arr[0, 1, :]
arr3 = arr[0, :, 0]
print(f'Первый слой:\n{arr1}')  
print(f'Вторая строка первого слоя: {arr2}')  
print(f'Первый столбец первого слоя: {arr3}')

Первый слой:
[[1 2]
 [3 4]]
Вторая строка первого слоя: [3 4]
Первый столбец первого слоя: [1 3]


In [55]:
# Задача № 34
# Выход: выведите все элементы в четных столбцах

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# ваш код

arr1 = arr[:, 1::2]
print(f'Элементы с четными столбцами:\n{arr1}')

Элементы с четными столбцами:
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [56]:
# Задача № 35
# Выход: выведите все элементы в нечетных столбцах

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# ваш код

arr1 = arr[:, ::2]
print(f'Элементы с нечетными столбцами:\n{arr1}')

Элементы с нечетными столбцами:
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [57]:
# Задача № 36
# Выход: выведите все элементы с нечетными строками

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# ваш код

arr1 = arr[::2, :]
print(f'Элементы с нечетными строками:\n{arr1}')

Элементы с нечетными строками:
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [58]:
# Задача № 37
# Выход: выделите подматрицу, состоящую из трех последних строк и двух первых столбцов

matrix = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25]])

# ваш код

submatrix = matrix[-3:, :2]
print(f'Матрица трех последних строк и двух первых столбцов:\n{submatrix}')

Матрица трех последних строк и двух первых столбцов:
[[11 12]
 [16 17]
 [21 22]]


In [59]:
# Задача № 38
# Выход: выделите подматрицу, состоящую из второй и третьей строк, а также третьего и четвёртого столбцов

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

# ваш код

submatrix = matrix[1:3, 2:]
print(f'Матрица из второй и третьей строк, а также третьего и четвёртого столбцов:\n{submatrix}')

Матрица из второй и третьей строк, а также третьего и четвёртого столбцов:
[[ 7  8]
 [11 12]]


In [61]:
# Задача № 39
# Выход: выведите подматрицу, состоящую из элементов с индексами от 1 до 2 по обеим осям, с помощью срезов

arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12], 
                [13, 14, 15, 16]])

# ваш код

submatrix = arr[1:3, 1:3]
print(f'Подматрица, состоящая из элементов с индексами от 1 до 2 по обеим осям:\n{submatrix}')

Подматрица, состоящая из элементов с индексами от 1 до 2 по обеим осям:
[[ 6  7]
 [10 11]]


In [62]:
# Задача № 40
# Выход: выведите элементы в обратном порядке с шагом 2 с помощью срезов

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# ваш код

submatrix = arr[::-2]
print(f'Элементы в обратном порядке с шагом 2:\n{submatrix}')

Элементы в обратном порядке с шагом 2:
[10  8  6  4  2]


In [63]:
# Задача № 41
# Выход: выберите подматрицу 2x2 в верхнем левом углу для каждой матрицы

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код

result = tensor[:, :2, :2]
print(f'Подматрица 2x2 в верхнем левом углу для каждой матрицы:\n{result}')

Подматрица 2x2 в верхнем левом углу для каждой матрицы:
[[[ 1  2]
  [ 4  5]]

 [[10 11]
  [13 14]]

 [[19 20]
  [22 23]]]


In [64]:
# Задача № 42
# Выход: выберите второй столбец для каждой строки в каждой матрице

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код

result = tensor[:, :, 1]
print(f'Второй столбец для каждой строки в каждой матрице:\n{result}')

Второй столбец для каждой строки в каждой матрице:
[[ 2  5  8]
 [11 14 17]
 [20 23 26]]


In [65]:
# Задача № 43
# Выход: выберите все элементы второй строки для каждой матрицы

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код

result = tensor[:, 1, :]
print(f'Все элементы вдоль второго измерения для каждой матрицы:\n{result}')

Все элементы вдоль второго измерения для каждой матрицы:
[[ 4  5  6]
 [13 14 15]
 [22 23 24]]


In [66]:
# Задача № 44
# Выход: выберите элементы в каждой матрице в нижнем правом углу, начиная с третьей строки
# и третьего столбца и до конца каждой матрицы. Обратите внимание - результат должен быть 
# трехмерным массивом, где каждая подматрица содержит элементы в нижнем правом углу соответствующей матрицы

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код

result = tensor[0:3, 2:, 2:]
print(f'Элементы в каждой матрице в нижнем правом угле:\n{result}')

Элементы в каждой матрице в нижнем правом угле:
[[[ 9]]

 [[18]]

 [[27]]]


In [67]:
# Задача № 45
# Выход: выберите четные строки и четные столбцы в каждой матрице

tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]], 

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# ваш код

result = tensor[0:3, 1::2, 1::2]
print(f'Четные строки и четные столбцы в каждой матрице:\n{result}')

Четные строки и четные столбцы в каждой матрице:
[[[ 5]]

 [[14]]

 [[23]]]


In [4]:
# Задача № 46
# Выход: выберите из массива arr все элементы, которые больше 3

arr = np.array([1, 2, 3, 4, 5, 6])

# ваш код

result = arr[arr > 3]
print(result)

[4 5 6]


In [5]:
# Задача № 47
# Выход: выберите из массива arr все четные числа

arr = np.array([1, 2, 3, 4, 5, 6])

# ваш код

result = arr[arr%2==0]
print(result)

[2 4 6]


In [6]:
# Задача № 48
# Выход: выберите из 2D массива matrix все элементы, которые больше 5

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# ваш код

result = matrix[matrix > 5]
print(result)

[6 7 8 9]


In [7]:
# Задача № 49
# Выход: инвертируйте булев массив arr

arr = np.array([True, False, True, False])

# ваш код

arr = list((False if elem==True else True for elem in arr))
result = np.array(arr) 
print(result)

[False  True False  True]


In [8]:
# Задача № 50
# Выход: выберите из массива arr все числа больше 2 и меньше 6

arr = np.array([1, 2, 3, 4, 5, 6])

# ваш код

result = arr[(arr>2) & (arr<6)]
print(result)

[3 4 5]


In [9]:
# Задача № 51
# Выход: выберите из 2D массива matrix все строки, в которых есть хотя бы одно число больше 7

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# ваш код

result = matrix[np.any(matrix>7, axis=1)]
print(result)

[[7 8 9]]


In [10]:
# Задача № 52
# Выход: покажите из массива arr все числа больше и равные 4

arr = np.array([1, 2, 3, 4, 5, 6])

# ваш код

result = arr[(arr==4) | (arr>4)]
print(result)

[4 5 6]


In [11]:
# Задача № 53
# Выход: замените в массиве arr все четные числа на 0

arr = np.array([1, 2, 3, 4, 5, 6])

# ваш код

arr[arr%2==0] = 0
print(arr)

[1 0 3 0 5 0]


In [12]:
# Задача № 54
# Выход: выберите из массива arr только те элементы,
# для которых соответствующее значение в массиве index_array равно True

arr = np.array([1, 2, 3, 4, 5, 6])
index_array = np.array([True, False, True, False, True, False])

# ваш код

result = arr[index_array==True]
print(result)

[1 3 5]


In [13]:
# Задача № 55
# Выход: выберите из 2D массива matrix все элементы, которые делятся на 3

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# ваш код

result = matrix[matrix%3==0]
print(result)

[3 6 9]


In [14]:
# Задача № 56
# Выход: проверить, содержит ли массив хотя бы одно положительное число и
# все ли элементы отрицательны. Необходимо проверить это с помощью функции check_array

array2 = np.array([-2, -4, -6, 8, -1])

# ваш код

def check_array(arr):
    has_positive = np.any(arr>0)
    all_negative = np.all(arr<0)

    return has_positive, all_negative

result = check_array(array2) # проверь массив array2 с помощью функции check_array

print(f"В массиве есть хотя бы одно положительное число: {result[0]}")
print(f"Все элементы массива отрицательны: {result[1]}")

В массиве есть хотя бы одно положительное число: True
Все элементы массива отрицательны: False


In [15]:
# Задача № 57
# Дано: набор данных о продажах товаров, представленный в виде двумерного массива sales_data_array.
#       Каждая строка представляет собой информацию о продажах для конкретного товара, а столбцы содержат
#       следующую информацию: номер товара, количество проданных единиц, и доход от продаж.
# Выход: 1. Есть ли хотя бы одна запись с нулевыми продажами (количество проданных единиц равно 0)?
#        2. Все ли товары имеют положительный доход от продаж?

sales_data_array = np.array([[1, 10, 100],
                             [2, 5, 50],
                             [3, 0, 0],
                             [4, 8, 80]])

# ваш код

def analyze_sales_data(sales_data):
    has_zero_sales = np.any(sales_data==0)
    all_positive_income = np.all(sales_data>0)

    return has_zero_sales, all_positive_income

result = analyze_sales_data(sales_data_array)

print(f"Есть ли товары с нулевыми продажами: {result[0]}")
print(f"Все ли товары имеют положительный доход: {result[1]}")

Есть ли товары с нулевыми продажами: True
Все ли товары имеют положительный доход: False


In [16]:
# Задача № 58
# Дано: массив data размером 5 x 5, заполненный случайными целыми числами от 0 до 9
# Выход: Замените все четные числа в массиве на 0, а все нечетные на 1.
#        Используйте булеву индексацию для создания масок, которые соответствуют этим условиям,
#        и примените их к массиву data.  

data = np.array([[6, 4, 8, 7, 9],
                 [0, 0, 1, 7, 2],
                 [5, 7, 9, 0, 4],
                 [5, 1, 2, 8, 6],
                 [9, 8, 3, 0, 3]])

# ваш код

even_mask = data%2==0
odd_mask = data%2!=0

data[even_mask] = 0
data[odd_mask] = 1
print(data)

[[0 0 0 1 1]
 [0 0 1 1 0]
 [1 1 1 0 0]
 [1 1 0 0 0]
 [1 0 1 0 1]]


In [17]:
# Задача № 59
# Дано: массив data размером 6 x 6, заполненный случайными целыми числами от 0 до 9
# Выход: Найдите среднее арифметическое всех элементов, которые находятся на главной
#        диагонали массива. Используйте булеву индексацию для создания маски, которая
#        соответствует этому условию, и примените ее к массиву data.

data = np.array([[8, 3, 9, 1, 9, 0],
                 [5, 4, 2, 7, 4, 2],
                 [0, 8, 7, 4, 3, 9],
                 [0, 9, 7, 1, 0, 1],
                 [7, 1, 0, 3, 9, 3],
                 [5, 8, 0, 4, 0, 6]])

# ваш код

mask = data[np.eye(6)==1]
mean = mask.mean()
print(f'Среднее арифметическое элементов на диагоналях: {mean:.2f}')

Среднее арифметическое элементов на диагоналях: 5.83


In [18]:
# Задача № 60
# Дано: массив data, содержащий информацию о студентах: имя, возраст, пол, курс и средний балл
# Выход: Найдите имена, средние баллы и другую информацию студентов, которые старше 20 лет,
#        женского пола и учатся на третьем курсе. Используйте булеву индексацию для создания
#        маски, которая соответствует этому условию, и примените ее к массиву data.  

data = np.array([
    ['Анна', 19, 'F', 1, 4.5],
    ['Борис', 21, 'M', 2, 3.7],
    ['Вера', 21, 'F', 3, 4.8],
    ['Глеб', 22, 'M', 4, 3.9],
    ['Дарья', 18, 'F', 1, 4.2],
    ['Егор', 23, 'M', 3, 4.1],
    ['Жанна', 21, 'F', 2, 4.6],
    ['Захар', 19, 'M', 1, 4.0]
])

# ваш код

mask = data[(data[:, 1].astype(int)>20) & (data[:, 2]=='F') & (data[:, 3].astype(int)==3)]
result = mask
print(result)

[['Вера' '21' 'F' '3' '4.8']]


In [19]:
# Задача № 61
# Выход: транспонируйте массив и сохраните результат в переменной transposed_arr

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15]])

# ваш код

transposed_arr = arr.T
print("Транспонированный массив:")
print(transposed_arr)

Транспонированный массив:
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [ ]:
# Задача № 62
# Выход: умножьте две матрицы arr1 и arr2, затем выведите результат

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

# ваш код

result = arr1.dot(arr2)
print("Результат умножения:")
print(result)

Результат умножения:
[[19 22]
 [43 50]]


In [ ]:
# Задача № 63
# Выход: измените форму массива arr размером 4x3 на (2, 6)

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])

# ваш код

reshaped_arr = arr.reshape((2, 6))
print("Массив после изменения формы:")
print(reshaped_arr)

Массив после изменения формы:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [22]:
# Задача № 64
# Выход: поменяйте местами оси массива

data = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10]])

# ваш код

data_new = np.swapaxes(data, 0, 1)
print("Изначальные данные:")
print(data)
print("Данные после перестановки:")
print(data_new)

Изначальные данные:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Данные после перестановки:
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [23]:
# Задача № 65
# Выход: создайте массив размером 2x8, заполненный значениями от 0 до 15

# ваш код

arr = np.reshape(np.arange(0, 16), (2, 8))
print("Массив:")
print(arr)

Массив:
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [24]:
# Задача № 66
# Выход: умножьте две матрицы arr1 и arr2, затем транспонируйте результат

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

# ваш код

result = (arr1 @ arr2)
transposed_result = result.transpose()
print("Транспонированный результат умножения:")
print(transposed_result)

Транспонированный результат умножения:
[[19 43]
 [22 50]]


In [27]:
# Задача № 67
# Выход: сохраните в переменной A транспонированный верхний левый квадрант:
# [[1 2]
#  [5 6]]

A = np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]])

# ваш код

A = A[:2, :2].T
print(A)

[[1 5]
 [2 6]]


In [28]:
# Задача № 68
# Выход: транспонировать только те строки, у которых первый элемент больше 3

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]])

# ваш код

condition = A[:, 0]>3
A[condition] = A[condition].T 
print("Матрица A после транспонирования строк с первым элементом больше 3:")
print(A)

Матрица A после транспонирования строк с первым элементом больше 3:
[[ 1  2  3  4]
 [ 5  9 13 17]
 [ 6 10 14 18]
 [ 7 11 15 19]
 [ 8 12 16 20]]


In [32]:
# Задача № 69
# Выход: Найдите абсолютные значения всех элементов массива

array = np.array([[-1, -2, -3], 
                  [4, -5, 6], 
                  [-7, 8, -9]])

# ваш код

result = np.abs(array)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
# Задача № 70
# Выход: вычислите квадратные корни для каждого элемента

array = np.array([4, 9, 16, 25])

# ваш код

result = np.sqrt(array)
print(result)

[2. 3. 4. 5.]


In [34]:
# Задача № 71
# Выход: найдите натуральные логарифмы для каждого элемента

array = np.array([2.718, 7.389, 20.086])

# ваш код

result = np.log(array)
print(result)

[0.99989632 1.99999241 3.00002305]


In [35]:
# Задача № 72
# Выход: определите знак каждого элемента

array = np.array([-3, 0, 5, -7])

# ваш код

result = np.sign(array)
print(result)

[-1  0  1 -1]


In [37]:
# Задача № 73
# Выход: округлите элементы массива в большую сторону

array = np.array([1.1, 2.7, 3.4, 4.9])

# ваш код

result = np.ceil(array)
print(result)

[2. 3. 4. 5.]


In [38]:
# Задача № 74
# Выход: округлите элементы массива в меньшую сторону

array = np.array([1.1, 2.7, 3.4, 4.9])

# ваш код

result = np.floor(array)
print(result)

[1. 2. 3. 4.]


In [39]:
# Задача № 75
# Выход: создайте булев массив, указывающий, является ли каждый элемент NaN

array = np.array([1.0, np.nan, 3.0, np.nan])

# ваш 

result = np.isnan(array)
print(result)

[False  True False  True]


In [40]:
# Задача № 76
# Выход: найдите дробную и целую часть массива

array = np.array([2.5, -3.7, 4.2])

# ваш код

fractional_part, integer_part = np.modf(array)
print(f'Дробная часть: {fractional_part}')
print(f'Целая часть: {integer_part}')

Дробная часть: [ 0.5 -0.7  0.2]
Целая часть: [ 2. -3.  4.]


In [41]:
# Задача № 77
# Выход: возведите каждый элемент в квадрат

array = np.array([2, 4, 6, 8])

# ваш код

result = np.square(array)
print(result)

[ 4 16 36 64]


In [42]:
# Задача № 78
# Выход: возведите каждый элемент в квадрат и определите знак полученных квадратов

array = np.array([-2, 0, 4, -6])

# ваш код

squares = np.square(array)
result = np.sign(squares)
print(result)

[1 0 1 1]


In [43]:
# Задача № 79
# Выход: найдите абсолютные значения и затем вычислите квадратные корни для каждого элемента

array = np.array([-9, 16, -25, 36])

# ваш код

absolute_values = np.abs(array)
result = np.sqrt(absolute_values)
print(result)

[3. 4. 5. 6.]


In [2]:
# Задача № 80
# Выход: напишите программу для выполнения поэлементного сложения массивов

array1 = np.array([10, 15, 20, 25])
array2 = np.array([2, 3, 4, 5])

# ваш код

result = array1+array2 
print("Результат сложения массивов:", result)

Результат сложения массивов: [12 18 24 30]


In [3]:
# Задача № 81
# Выход: напишите программу для выполнения поэлементного вычитания второго массива из первого

array1 = np.array([15, 25, 35, 45])
array2 = np.array([5, 10, 15, 20])

# ваш код

result = array1-array2
print("Результат вычитания массивов:", result)

Результат вычитания массивов: [10 15 20 25]


In [4]:
# Задача № 82
# Выход: напишите программу для выполнения поэлементного умножения массивов

array1 = np.array([2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2])

# ваш код

result = array1 * array2
print("Результат умножения массивов:", result)

Результат умножения массивов: [10 12 12 10]


In [5]:
# Задача № 83
# Выход: напишите программу для выполнения поэлементного деления первого массива на второй

array1 = np.array([10, 20, 30, 40])
array2 = np.array([2, 4, 6, 8])

# ваш код

result_divide = array1 / array2 
print("Результат деления массивов:", result_divide)

Результат деления массивов: [5. 5. 5. 5.]


In [ ]:
# Задача № 84
# Выход: напишите программу, которая выполняет операцию возведения каждого элемента
#        первого массива nums_base в степень соответствующего элемента второго массива exponents

nums_base = np.array([2, 3, 4, 5])
exponents = np.array([3, 2, 1, 4])

# ваш код

result = np.power(nums_base, exponents)
print("Результат возведения в степень:", result)

Результат возведения в степень: [  8   9   4 625]


In [7]:
# Задача № 85
# Выход: напишите программу для нахождения максимальных значений из двух массивов поэлементно

array1 = np.array([10, 15, 8, 20])
array2 = np.array([5, 12, 15, 10])

# ваш код

result_maximum = np.maximum(array1, array2) 
print("Максимальные значения поэлементно:", result_maximum)

Максимальные значения поэлементно: [10 15 15 20]


In [8]:
# Задача № 86
# Выход: напишите программу для нахождения остатков от деления элементов первого
#        массива на соответствующие элементы второго массива

array1 = np.array([10, 15, 8, 20])
array2 = np.array([3, 4, 2, 7])

# ваш код

result_mod = np.mod(array1, array2)
print("Остатки от деления массивов:", result_mod)

Остатки от деления массивов: [1 3 0 6]


In [9]:
# Задача № 87
# Выход: напишите программу для копирования знаков значений из второго массива в значения первого массива

array1 = np.array([10, -15, 8, -20])
array2 = np.array([-3, 4, -2, 7])

# ваш код

result_copysign = np.copysign(array1, array2)
print("Результат копирования знаков:", result_copysign)

Результат копирования знаков: [-10.  15.  -8.  20.]


In [10]:
# Задача № 88
# Дано: два массива, представляющих собой высоту и ширину изображений
# Выход: напишите программу для расчета общего количества пикселей в каждом изображении

heights = np.array([720, 1080, 480, 960])
widths = np.array([1280, 1920, 640, 1280])

# ваш код

total_pixels = heights * widths
print("Общее количество пикселей в каждом изображении:", total_pixels)

Общее количество пикселей в каждом изображении: [ 921600 2073600  307200 1228800]


In [11]:
# Задача № 89
# Дано: Вы разрабатываете программу для анализа данных о скорости интернет-подключения
# Выход: напишите программу для определения максимальной и минимальной скорости
#        в каждом измерении (загрузка и выгрузка)

download_speeds = np.array([50, 60, 45, 70, 55])
upload_speeds = np.array([30, 40, 25, 50, 35])

# ваш код

max_speeds = np.maximum(download_speeds, upload_speeds)
min_speeds = np.minimum(download_speeds, upload_speeds)
print("Максимальные скорости:", max_speeds)
print("Минимальные скорости:", min_speeds)

Максимальные скорости: [50 60 45 70 55]
Минимальные скорости: [30 40 25 50 35]


In [12]:
# Задача № 90
# Дано: массив цен prices и ставка НДС vat_rate
# Выход: нужно рассчитать стоимость товаров с учетом НДС

prices = np.array([25.50, 12.75, 18.90, 30.25, 15.60])
vat_rate = 0.20

# ваш код

prices_with_vat = prices * (1+vat_rate)
print("Стоимость товаров с НДС:", prices_with_vat)

Стоимость товаров с НДС: [30.6  15.3  22.68 36.3  18.72]


In [13]:
# Задача № 91
# Дано: массив, представляющий собой распределение годового дохода компании в миллионах долларов
# Выход: напишите программу для вычисления налогов на прибыль (20% от дохода) и
#        оставшейся чистой прибыли для каждого элемента

annual_income = np.array([15, 20, 25, 18, 22])
tax_rate = 0.20

# ваш код

taxes = annual_income * tax_rate
net_income = annual_income - taxes
print("Налоги на прибыль:", taxes)
print("Чистая прибыль:", net_income)

Налоги на прибыль: [3.  4.  5.  3.6 4.4]
Чистая прибыль: [12.  16.  20.  14.4 17.6]


In [14]:
# Задача № 92
# Дано: массив, представляющий собой скорости движения транспортного средства в км/ч
# Выход: напишите программу для определения времени в пути для каждой скорости при
#        преодолении расстояния 150 км с учетом замедления движения на 20%.
#        Округлите  результат вниз, возвращая только целую часть.

speeds = np.array([60, 75, 90, 100, 80, 65])
distance = 150
slowdown_rate = 0.20

# ваш код

adjusted_speeds = speeds * (1-slowdown_rate)
travel_times = np.floor(150 / adjusted_speeds)
print("Время в пути для каждой скорости:", travel_times)

Время в пути для каждой скорости: [3. 2. 2. 1. 2. 2.]


In [15]:
# Задача № 93
# Дано: массив целых чисел
# Выход: создать новый массив, содержащий булевы значения (True/False),
#        которые указывают, является ли каждый элемент исходного массива четным

arr = np.array([5, 10, 15, 20, 25])

# ваш код

result = arr%2==0
print(result)

[False  True False  True False]


In [16]:
# Задача № 94
# Выход: получите булев массив, который показывает, в каких местах первый массив
#        содержит большие значения, чем второй

a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

# ваш код

result = np.greater(a, b)
print(result)

[False False  True]


In [17]:
# Задача № 95
# Выход: используйте сравнение с учетом равенства, чтобы получить булев массив,
#        который показывает, где первый массив содержит значения, большие или
#        равные соответствующим значениям второго

a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

# ваш код

result = np.greater_equal(a, b)
print(result)

[False  True  True]


In [18]:
# Задача № 96
# Выход: получите булев массив, который показывает, в каких местах первый массив
#        содержит меньшие значения, чем второй

a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

# ваш код

result = np.less(a, b)
print(result)

[ True False False]


In [19]:
# Задача № 97
# Выход: получите булев массив, показывающий, где соответствующие элементы не равны

a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

# ваш код

result = np.not_equal(a, b)
print(result)

[ True False  True]


In [20]:
# Задача № 98
# Выход: найти все элементы массива, которые не равны числу 3

arr = np.array([[0, 1, 2], 
                [3, 4, 5]])

# ваш код

result = np.not_equal(arr, 3)
print(result)

[[ True  True  True]
 [False  True  True]]


In [21]:
# Задача № 99
# Дано: бинарные массивы, представляющие наличие (1) или отсутствие (0) двух событий
# Выход: определите, в каких случаях произошло ровно одно из событий

event1 = np.array([1, 0, 0, 1, 0])
event2 = np.array([0, 1, 0, 1, 1])

# ваш код

exactly_one_event = np.logical_xor(event1, event2)
print(exactly_one_event)

[ True  True False False  True]


In [23]:
# Задача № 100
# Выход: получите новый массив, где каждый элемент равен 1, если классификации совпадают
#        и 0 в противном случае

classification1 = np.array([[1, 0, 1], 
                            [0, 1, 0]])
classification2 = np.array([[1, 0, 0], 
                            [0, 1, 1]])

# ваш код

result = np.where(np.equal(classification1, classification2), 1, 0)
print(result)

[[1 1 0]
 [1 1 0]]


In [24]:
# Задача № 101
# Дано: массив чисел secret_codes, представляющих собой последовательность некоторых секретных кодов.
#       Не все коды были переданы вам, а только часть provided_codes.
# Выход: нужно определить, какие коды вам не предоставили

secret_codes = np.array([15, 23, 7, 42, 18, 10, 7, 29])
provided_codes = np.array([23, 7, 18, 7])

# ваш код

missing_codes = secret_codes[np.logical_not(np.isin(secret_codes, provided_codes))]
print("Отсутствующие коды:", missing_codes)

Отсутствующие коды: [15 42 10 29]


In [25]:
# Задача № 102
# Дано: два массива, celsius_temps представляющий температуру в градусах Цельсия
#       и days представляющий дни в которые эта температура была зарегистрирована
# Выход: определить, в какие дни температура в Фаренгейтах была выше 90, а в Цельсиях не ниже 30

celsius_temps = np.array([25, 32, 28, 35, 30]) 
days = np.array(['понедельник', 'вторник', 'среда', 'четверг', 'пятница']) 

# ваш код

fahrenheit_temps = celsius_temps*9/5 + 32
hot_days_fahrenheit_temps = days[fahrenheit_temps>90]
hot_days_celsius_temps = days[celsius_temps>=30]
print(f'Температура выше 90 по Фаренгейту: {hot_days_fahrenheit_temps}')
print(f'Температура не ниже 30 Цельсия: {hot_days_celsius_temps}')

Температура выше 90 по Фаренгейту: ['четверг']
Температура не ниже 30 Цельсия: ['вторник' 'четверг' 'пятница']


In [26]:
# Задача № 103
# Дано: массив, представляющий возрастающую последовательность чисел
# Выход: определить, какие числа удовлетворяют критериям: больше 10 и не больше 30, и не равны 15

numbers = np.array([5, 12, 15, 20, 25, 30, 35])

# ваш код

condition1 = (numbers>10) & (numbers<=30)
condition2 = numbers != 15
filtered_numbers = numbers[condition1 & condition2]
print(f'Числа, удовлетворяющие условиям: {filtered_numbers}')

Числа, удовлетворяющие условиям: [12 20 25 30]


In [27]:
# Задача № 104
# Выход: выведите четные числа в массиве

numbers = np.array([2, 5, 8, 12, 15, 20, 23])

# ваш код

even_numbers = numbers[numbers%2==0]
print(f'Четные числа: {even_numbers}')

Четные числа: [ 2  8 12 20]


In [28]:
# Задача № 105
# Выход: замените все отрицательные значения в массиве arr на 0

arr = np.array([-1, 2, -3, 4, -5])

# ваш код

modified_arr = np.where(arr<0, 0, arr)
print("Исходный массив:")
print(arr)
print("Модифицированный массив:")
print(modified_arr)

Исходный массив:
[-1  2 -3  4 -5]
Модифицированный массив:
[0 2 0 4 0]


In [29]:
# Задача № 106
# Выход: замените все нечетные числа на 0

arr = np.array([1, 2, 3, 4, 5, 6])

# ваш код

modified_arr = np.where(arr%2!=0, 0, arr)
print("Исходный массив:")
print(arr)
print("Модифицированный массив:")
print(modified_arr)

Исходный массив:
[1 2 3 4 5 6]
Модифицированный массив:
[0 2 0 4 0 6]


In [30]:
# Задача № 107
# Выход: создайте новый массив, который содержит элементы из arr1, если они больше 0,
#        и элементы из arr2 в противном случае

arr1 = np.array([1, -2, 3, -4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# ваш код

result_arr = np.where(arr1>0, arr1, arr2)
print("Итоговый массив:")
print(result_arr)

Итоговый массив:
[ 1 20  3 40  5]


In [31]:
# Задача № 108
# Выход: замените все отрицательные значения в двумерном массиве matrix на 0

matrix = np.array([[1, -2, 3], 
                   [-4, 5, -6], 
                   [7, 8, -9]])

# ваш код

modified_matrix = np.where(matrix<0, 0, matrix)
print("Модифицированная матрица:")
print(modified_matrix)

Модифицированная матрица:
[[1 0 3]
 [0 5 0]
 [7 8 0]]


In [32]:
# Задача № 109
# Выход: создайте новый массив, который содержит 'positive', если элемент положителен,
#        и 'non-positive' в противном случае

arr = np.array([1, -2, 0, 3, -4])

# ваш код

result_arr = np.where(arr>0, 'positive', 'non-positive')
print("Массив arr:")
print(arr)
print("Итоговый массив:")
print(result_arr)

Массив arr:
[ 1 -2  0  3 -4]
Итоговый массив:
['positive' 'non-positive' 'non-positive' 'positive' 'non-positive']


In [33]:
# Задача № 110
# Выход: создайте новый массив,  который содержит 'A' для элементов больше 5,
#        'B' для элементов от 1 до 5 включительно и 'C' в противном случае

arr = np.array([3, 8, 1, 6, 0, 7])

# ваш код

result_arr = np.where(arr>5, 'A', np.where((1<=arr) & (arr<=5), 'B', 'C'))
print("Массив arr:")
print(arr)
print("Итоговый массив:")
print(result_arr)

Массив arr:
[3 8 1 6 0 7]
Итоговый массив:
['B' 'A' 'B' 'A' 'C' 'A']


In [34]:
# Задача № 111
# Выход: замените все значения, которые делятся и на 2, и на 3, на значение  -1

arr = np.array([2, 6, 9, 12, 15])

# ваш код

modified_arr = np.where((arr%2==0) & (arr%3==0), -1, arr)
print("Массив arr:")
print(arr)
print("Модифицированный массив:")
print(modified_arr)

Массив arr:
[ 2  6  9 12 15]
Модифицированный массив:
[ 2 -1  9 -1 15]


In [35]:
# Задача № 112
# Выход: замените положительные значения на их квадратные корни, а отрицательные на 0

arr = np.array([4, 9, 16, 25, 36])

# ваш код

modified_arr = np.where(arr>0, arr**0.5, 0)
print("Массив arr:")
print(arr)
print("Модифицированный массив:")
print(modified_arr)

Массив arr:
[ 4  9 16 25 36]
Модифицированный массив:
[2. 3. 4. 5. 6.]


In [36]:
# Задача № 113
# Выход: создайте маску, которая содержит True для элементов больше 3 и False в противном случае

arr = np.array([1, 4, 2, 7, 5])

# ваш код

mask = np.where(arr>3, True, False)
print("Массив arr:")
print(arr)
print("Маска:")
print(mask)

Массив arr:
[1 4 2 7 5]
Маска:
[False  True False  True  True]


In [37]:
# Задача № 114
# Выход: замените значения в arr1 на значения из arr2, если они отрицательные

arr1 = np.array([1, -2, 3, -4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# ваш код

result_arr = np.where(arr1<0, arr2, arr1)
print("Массив arr1:")
print(arr1)
print("Массив arr2:")
print(arr2)
print("Итоговый массив:")
print(result_arr)

Массив arr1:
[ 1 -2  3 -4  5]
Массив arr2:
[10 20 30 40 50]
Итоговый массив:
[ 1 20  3 40  5]


In [38]:
# Задача № 115
# Выход: создайте новый массив, который содержит квадраты элементов arr,
#        если элемент положителен, и кубы элементов arr, если элемент отрицателен

arr = np.array([2, -3, 4, -5, 6])

# ваш код

new_arr = np.where(arr>0, arr**2, arr**3)
print("Массив arr:")
print(arr)
print("Новый массив:")
print(new_arr)

Массив arr:
[ 2 -3  4 -5  6]
Новый массив:
[   4  -27   16 -125   36]


In [39]:
# Задача № 116
# Выход: выберите значения, которые нечетные и больше 3 или четные и меньше 0.
#        Остальные значения замените на ноль

arr = np.array([-2, 3, 5, -4, 6, 1])

# ваш код

selected_values = np.where(((arr%2!=0) & (arr>3)) | ((arr)%2==0) & (arr<0), arr, 0)
print("Массив arr:")
print(arr)
print("Выбранные значения:")
print(selected_values)

Массив arr:
[-2  3  5 -4  6  1]
Выбранные значения:
[-2  0  5 -4  0  0]


In [40]:
# Задача № 117
# Выход: найти сумму и среднее значение элементов массива

arr = np.array([2, 4, 6, 8, 10])

# ваш код

result = arr.sum()
result2 = arr.mean()
print(f"Сумма: {result} \nСреднее: {result2}")

Сумма: 30 
Среднее: 6.0


In [41]:
# Задача № 118
# Выход: минимальное и максимальное значения в массиве

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

# ваш код

value1 = arr.min()
value2 = arr.max()
print(f"Минимум: {value1}\nМаксимум: {value2}")

Минимум: 1
Максимум: 9


In [42]:
# Задача № 119
# Выход: найти стандартное отклонение и дисперсию элементов массива

arr = np.array([5, 8, 12, 15, 18])

# ваш код

result1 = arr.std()
result2 = arr.var()
print(f"Стандартное отклонение: {result1}\nДисперсия: {result2}")

Стандартное отклонение: 4.673328578219169
Дисперсия: 21.840000000000003


In [43]:
# Задача № 120
# Выход: найти индекс минимального и максимального значения в массиве

arr = np.array([22, 13, 45, 7, 19])

# ваш код

result1 = arr.argmin() 
result2 = arr.argmax()
print(f"Индекс минимального значения: {result1}\nИндекс максимального значения: {result2}")

Индекс минимального значения: 3
Индекс максимального значения: 2


In [44]:
# Задача № 121
# Выход: найти кумулятивную сумму и кумулятивное произведение в массиве

arr = np.array([1, 2, 3, 4, 5])

# ваш код

result1 = arr.cumsum()
result2 = arr.cumprod()
print(f"Кумулятивную сумма: {result1}\nКумулятивное произведение: {result2}")

Кумулятивную сумма: [ 1  3  6 10 15]
Кумулятивное произведение: [  1   2   6  24 120]


In [45]:
# Задача № 122
# Дано: данные о ежедневных изменениях стоимости акций компании
# Выход: найти изменение цен за каждый день, а также дни с минимальным и максимальным изменением

stock_prices = np.array([50, 55, 60, 52, 48, 65, 70])
days = np.array(['понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота', 'воскресенье'])

# ваш код

daily_returns = np.diff(stock_prices)
best_day = days[daily_returns.argmax()+1]
worst_day = days[daily_returns.argmin()+1]
print(f"Изменения цен за день: {daily_returns}")
print(f"Лучший день: {best_day}")
print(f"Худший день: {worst_day}")

Изменения цен за день: [ 5  5 -8 -4 17  5]
Лучший день: суббота
Худший день: четверг


In [46]:
# Задача № 123
# Дано: данные о температуре воздуха в течение года
# Выход: найти размах температур, а также индексы минимальной и максимальной температуры

temperature_data = np.array([20, 22, 25, 18, 30, 28, 35, 22, 15, 10, 5, 12])

# ваш код

temperature_range = np.ptp(temperature_data)
coldest_day = temperature_data.argmin()
hottest_day = temperature_data.argmax()
print(f"Размах температур: {temperature_range}")
print(f"Индекс самого холодного дня: {coldest_day}")
print(f"Индекс самого теплого дня: {hottest_day}")

Размах температур: 30
Индекс самого холодного дня: 10
Индекс самого теплого дня: 6


In [48]:
# Задача № 124
# Дано: массив доходов отдельных инвесторов за год
# Выход: 1. Найти медиану доходов.
#        2. Определить, сколько инвесторов заработали выше медианного значения, а сколько ниже.
#        3. Найти разброс доходов для инвесторов, заработавших выше медианы.

income_data = np.array([40, 55, 60, 75, 80, 85, 90, 100, 120, 150])

# ваш код

median_income = np.median(income_data)
above_median = income_data[income_data>median_income]
below_median = income_data[income_data<median_income]
income_range_above_median = np.ptp(above_median)
print("Медиана доходов:", median_income)
print("Инвесторы, заработавшие выше медианы:", above_median)
print("Инвесторы, заработавшие ниже медианы:", below_median)
print("Разброс доходов для инвесторов, заработавших выше медианы:", income_range_above_median)

Медиана доходов: 82.5
Инвесторы, заработавшие выше медианы: [ 85  90 100 120 150]
Инвесторы, заработавшие ниже медианы: [40 55 60 75 80]
Разброс доходов для инвесторов, заработавших выше медианы: 65


In [49]:
# Задача № 125
# Выход: 1. Найти среднюю стоимость акций каждой компании за все дни.
#        2. Определить компанию с максимальной волатильностью (наибольшим размахом цен).
#        3. Найти день с наибольшим общим изменением в стоимости акций всех компаний.

stock_prices = np.array([
    [110, 112, 108],
    [115, 118, 120],
    [108, 110, 105],
    [122, 121, 124],
    [128, 130, 125],
    [133, 132, 134],
    [129, 127, 130]
])

# ваш код

average_prices = np.round(stock_prices.mean(axis=0), 2)
volatility = np.ptp(stock_prices, axis=0)
most_volatile_company = np.argmax(volatility)
total_daily_change = np.diff(stock_prices.sum(axis=1))
day_with_max_change = np.argmax(total_daily_change)+1
print("Средняя стоимость акций каждой компании:", average_prices) 
print("Индекс самой волатильной компании:", most_volatile_company) 
print("Индекс дня с наибольшим изменением в стоимости акций:", day_with_max_change)

Средняя стоимость акций каждой компании: [120.71 121.43 120.86]
Индекс самой волатильной компании: 2
Индекс дня с наибольшим изменением в стоимости акций: 3


In [50]:
# Задача № 126
# Выход: Найти средний возраст пациентов. Определить пациента с самым высоким
#        уровнем холестерина и самым низким давлением

# Заданные данные (1-й столбец: возраст, 2-й столбец: уровень холестерина, 3-й столбец: давление)
medical_data = np.array([
    [30, 200, 120],
    [45, 220, 130],
    [35, 190, 110]
])

# ваш код

average_age = np.round(np.mean(medical_data[:, 0]), 1)
max_cholesterol_patient = medical_data[np.argmax(medical_data[:, 1]), :]
min_pressure_patient = medical_data[np.argmin(medical_data[:, 2]), :]
print(f"Средний возраст пациентов: {average_age}")
print("Пациент с самым высоким уровнем холестерина:", max_cholesterol_patient)
print("Пациент с самым низким давлением:", min_pressure_patient)

Средний возраст пациентов: 36.7
Пациент с самым высоким уровнем холестерина: [ 45 220 130]
Пациент с самым низким давлением: [ 35 190 110]


In [51]:
# Задача № 127
# Дано: массив student_scores, с оценками студентов (каждая строка один студент)
# Выход: найти средний балл за каждую задачу. Определить студента с наивысшим средним баллом.
#        Найти задачу с наименьшей дисперсией баллов.

student_scores = np.array([
    [5, 4, 3],  # Оценки первого студента за три задачи
    [3, 2, 4],  # Оценки второго студента за три задачи
    [5, 5, 3]   # Оценки третьего студента за три задачи
])

# ваш код

average_scores = np.round(np.mean(student_scores, axis=0), 1)
highest_avg_student = np.argmax(np.mean(student_scores, axis=1))
min_variability_task = np.argmin(np.var(student_scores, axis=0))
print("Средний балл за каждую задачу:", average_scores)
print("Индекс cтудента с наивысшим средним баллом:", highest_avg_student)
print("Индекс задачи с наименьшей дисперсией баллов:", min_variability_task)

Средний балл за каждую задачу: [4.3 3.7 3.3]
Индекс cтудента с наивысшим средним баллом: 2
Индекс задачи с наименьшей дисперсией баллов: 2


In [52]:
# Задача № 128
# Выход: напишите функцию most_frequent_number(arr), которая находит наиболее
#        часто встречающееся число и количество его вхождений

arr = np.array([1, 2, 3, 1, 2, 1, 4, 5, 4, 3, 3])

# ваш код

def most_frequent_number(arr):
    bin_counts = np.bincount(arr)
    most_frequent_index = np.argmax(bin_counts)
    occurrences = bin_counts[most_frequent_index]
    return most_frequent_index, occurrences

result_number, result_occurrences = most_frequent_number(arr)

print(f"Наиболее часто встречающееся число: {result_number}")
print(f"Количество вхождений: {result_occurrences}")

Наиболее часто встречающееся число: 1
Количество вхождений: 3


In [53]:
# Задача № 129
# Выход: отсортируйте массив по возрастанию

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])

# ваш код

sorted_arr = np.sort(arr)
print("Исходный массив:", arr)
print("Отсортированный массив по возрастанию:", sorted_arr)

Исходный массив: [3 1 4 1 5 9 2 6]
Отсортированный массив по возрастанию: [1 1 2 3 4 5 6 9]


In [54]:
# Задача № 130
# Выход: найдите элементы, которые встречаются только в arr1, но не в arr2

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

# ваш код

setdiff_arr = np.setdiff1d(arr1, arr2)
print("Элементы, встречающиеся только в arr1:", setdiff_arr)

Элементы, встречающиеся только в arr1: [1 2]


In [55]:
# Задача № 131
# Выход: отсортируйте массив и выведите первые k элементов этого массива

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
k = 4

# ваш код

partial_sorted_arr = np.sort(arr)[:k]
print("Исходный массив:", arr)
print(f"Частично отсортированный массив (первые {k} элемента):", partial_sorted_arr)

Исходный массив: [3 1 4 1 5 9 2 6]
Частично отсортированный массив (первые 4 элемента): [1 1 2 3]


In [56]:
# Задача № 132
# Выход: найдите элементы, которые встречаются только в одном из массивов, но не в обоих

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

# ваш код

setxor_arr = np.setxor1d(arr1, arr2)
print("Элементы, встречающиеся только в одном из массивов:", setxor_arr)

Элементы, встречающиеся только в одном из массивов: [1 2 6 7]


In [57]:
# Задача № 133
# Выход: отсортируйте массив тремя способами:
#        1. по имени в алфавитном порядке
#        2. по возрасту в порядке возрастания
#        3. по возрасту в порядке убывания

people = np.array([('John', 28), 
                   ('Sam', 22), 
                   ('Smith', 25), 
                   ('Jones', 30)], 
            dtype=[('name', 'S10'), ('age', int)])

# ваш код

sorted_people_by_name = np.sort(people, order='name')
sorted_people_by_age = np.sort(people, order='age')
sorted_people_by_age_desc = np.sort(people, order='age')[::-1]
print("Исходный массив структур:")
print(people)
print("\nСортировка по полю 'name':")
print(sorted_people_by_name)
print("\nСортировка по полю 'age' в порядке возрастания:")
print(sorted_people_by_age)
print("\nСортировка по полю 'age' в порядке убывания:")
print(sorted_people_by_age_desc)

Исходный массив структур:
[(b'John', 28) (b'Sam', 22) (b'Smith', 25) (b'Jones', 30)]

Сортировка по полю 'name':
[(b'John', 28) (b'Jones', 30) (b'Sam', 22) (b'Smith', 25)]

Сортировка по полю 'age' в порядке возрастания:
[(b'Sam', 22) (b'Smith', 25) (b'John', 28) (b'Jones', 30)]

Сортировка по полю 'age' в порядке убывания:
[(b'Jones', 30) (b'John', 28) (b'Smith', 25) (b'Sam', 22)]


In [58]:
# Задача № 134
# Выход: выведите уникальные элементы каждого массива, а затем найдите пересечение этих уникальных элементов

arr1 = np.array([1, 2, 'apple', 'orange', 5, 'orange', 'apple', 'orange'])
arr2 = np.array([3, 'apple', 'banana', 6, 7, 1, 'mango'])

# ваш код

unique_arr1 = np.unique(arr1)
unique_arr2 = np.unique(arr2)
intersection =  np.intersect1d(arr1, arr2)
print("Уникальные элементы arr1:", unique_arr1)
print("Уникальные элементы arr2:", unique_arr2)
print("Пересечение уникальных элементов:", intersection)

Уникальные элементы arr1: ['1' '2' '5' 'apple' 'orange']
Уникальные элементы arr2: ['1' '3' '6' '7' 'apple' 'banana' 'mango']
Пересечение уникальных элементов: ['1' 'apple']


In [59]:
# Задача № 135
# Выход: найдите уникальные элементы, а также их индексы в порядке их появления,
#        а затем выведите наименьший и наибольший элементы

arr = np.array([3, 2, 4, 1, 5, 2, 6, 4, 7])

# ваш код

unique_elements = np.unique(arr, return_index=True)
min_element = np.min(arr)
max_element = np.max(arr)
print("Уникальные элементы:", unique_elements[0])
print("Индексы вхождения уникальных элементов:", unique_elements[1])
print("Наименьший элемент:", min_element)
print("Наибольший элемент:", max_element)

Уникальные элементы: [1 2 3 4 5 6 7]
Индексы вхождения уникальных элементов: [3 1 0 2 4 6 8]
Наименьший элемент: 1
Наибольший элемент: 7


In [60]:
# Задача № 137
# Выход: найти и вывести объединение уникальных элементов массивов,
#        а также определить те числа, которые встречаются и в arr1, и в arr2

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

# ваш код

unique_arr1 = np.unique(arr1)
unique_arr2 = np.unique(arr2)
union = np.union1d(unique_arr1, unique_arr2)
in_arr1_mask = np.in1d(union, arr1)
in_arr2_mask = np.in1d(union, arr2)
common_elements_mask = np.in1d(union, np.intersect1d(arr1, arr2))
common_elements = np.intersect1d(arr1, arr2)
print("Объединение уникальных элементов:", union)
print("Маска для вхождения в arr1:", in_arr1_mask)
print("Маска для вхождения в arr2:", in_arr2_mask)
print("Маска для общих элементов:", common_elements_mask)
print("Элементы, встречающиеся и в arr1, и в arr2:", common_elements)

Объединение уникальных элементов: [1 2 3 4 5 6 7]
Маска для вхождения в arr1: [ True  True  True  True  True False False]
Маска для вхождения в arr2: [False False  True  True  True  True  True]
Маска для общих элементов: [False False  True  True  True False False]
Элементы, встречающиеся и в arr1, и в arr2: [3 4 5]


In [ ]:
# Задача № 137
# Выход: найдите уникальные элементы массива.
#        Затем удалите из этого массива все уникальные элементы, которые больше заданного порога.

arr = np.array([3, 2, 4, 1, 5, 2, 6, 4, 7])
threshold = 4  # порог для удаления элементов

# ваш код

unique_elements = np.unique(arr)
indices_to_remove = np.where(unique_elements>threshold)
filtered_arr = np.delete(unique_elements, indices_to_remove)
print("Исходный массив:", arr)
print("Уникальные элементы:", unique_elements)
print("Массив после удаления элементов больше", threshold, ":", filtered_arr)

Исходный массив: [3 2 4 1 5 2 6 4 7]
Уникальные элементы: [1 2 3 4 5 6 7]
Массив после удаления элементов больше 4 : [1 2 3 4]


In [63]:
# Задача № 138
# Выход: удалите из массива arr все элементы, которые встречаются более одного раза

arr = np.array([3, 2, 4, 1, 5, 2, 6, 4, 7])

# ваш код

unique_elements, counts = np.unique(arr, return_counts=True)
elements_to_remove = unique_elements[counts>1]
filtered_arr = np.setdiff1d(arr, elements_to_remove, assume_unique=True)
print("Исходный массив:", arr)
print("Массив после удаления элементов, встречающихся более одного раза:", filtered_arr)

Исходный массив: [3 2 4 1 5 2 6 4 7]
Массив после удаления элементов, встречающихся более одного раза: [3 1 5 6 7]
