Варианты решения задач

In [1]:
import numpy as np

In [ ]:
# Задача № 1 
# Дано два целых числа
# Выход: массив NumPy из этих чисел

a = 3
b = 2

# ваш код

arr = np.array((a, b))
print(arr)

[3 2]


In [ ]:
# Задача № 2 
# Дано 3 вещественных числа
# Выход: массив NumPy из этих чисел

a = 3.3
b = 3
c = 2.2

# ваш код

arr = np.array((a, b, c))
print(arr)

[3.3 3.  2.2]


In [ ]:
# Задача № 3
# Дано двенадцать чисел: координаты точек начала и конца первого вектора x1, y1, z1, x2, y2, z2 и
# координаты точек начала и конца второго вектора x3, y3, z3, x4, y4, z4
# Выход: True, если вектора равны, иначе False.

x1, y1, z1, x2, y2, z2 = 1, 2, 3, 3, 4, 5
x3, y3, z3, x4, y4, z4 = -3, 3, 2, -1, 5, 4

# ваш код

a = np.array([x2-x1, y2-y1, z2-z1])
b = np.array([x4-x3, y4-y3, z4-z3])
print(not False in (a == b))

True


In [ ]:
# Задача № 4
# Дано натуральное число и вектор с координатами [0.5, 0.25, 0.125, ..., 0.5^n]
# Выход: L1 норма вектора

n = 4

# ваш код

v = np.array([0.5**i for i in range(1, n+1)])
print(np.linalg.norm(v, ord=1))


0.9375


In [ ]:
# Задача № 5
# Дано координаты векторов
# Выход: Сумма векторов

a = np.array((1, 2, 1))
b = np.array((-1, 2, 0))

# ваш код

print(a+b)

[0 4 1]


In [ ]:
# Задача № 6
# Дано восемь чисел: координаты точек начала и конца первого вектора x1, y1, x2, y2 и
# координаты точек начала и конца второго вектора x3, y3, x4, y4
# Выход: модуль вектора суммы векторов

x1, y1, x2, y2 = 0, 0, 0, 0
x3, y3, x4, y4 = 0, 0, 0, 5

# ваш код

a = np.array([x2-x1, y2-y1])
b = np.array([x4-x3, y4-y3])
print(np.linalg.norm(a+b))

5.0


In [ ]:
# Задача № 7
# Дано два вектора
# Выход: модуль разности векторов

a = np.array((2, 3, 2))
b = np.array((1, 3, 2))

# ваш код

c = a-b
print(np.linalg.norm(c))

1.0


In [3]:
# Задача № 8
# Дано координаты точек A, B, D параллелограмма ABCD
# Выход: длины диагоналей AC, BD

A = np.array([0, 0])
B = np.array([0, 4])
D = np.array([3, 0])

# ваш код

BD = np.linalg.norm(B-D)
AD = np.linalg.norm(A-D)
AB = np.linalg.norm(A-B)
AC = (2*(AD**2 + AB**2) - BD**2)**0.5
print(AC, BD)

5.0 5.0


In [4]:
# Задача № 9
# Дано координаты сил, действующих на материальную точку
# Выход: модуль равнодействующей сил

a = np.array([2, 0, 0])
b = np.array([-2, 0, 0])

# ваш код

print(np.linalg.norm(a+b))


0.0


In [ ]:
# Задача № 10
# Дано координаты двух векторов a и b
# Выход: модуль вектора, полученного вычитанием вектора b умноженного на два из вектора a умноженного на три

a = np.array([0, 0, 0])
b = np.array([0, 2, 0])

# ваш код

c = 3*a - 2*b
print(np.linalg.norm(c))

4.0


In [10]:
# Задача № 11
# Дано координаты двух векторов a и b
# Выход: True, если вектора коллиенарны, False в противном случае

a = np.array([1, 2, 3])
b = np.array([2, 4, 6])

# ваш код

print(np.all(np.cross(a, b) == 0))

True


In [15]:
# Задача № 12
# Дано координаты точек A, B, целое число k
# Выход: координаты точки С, которая делит отрезок АВ в отношении k

A = np.array([1, -2, 3])
B = np.array([0, 3, 2])
k = 5

# ваш код

C = np.round((A+k*B)/(k+1), 2)
print(C)

[0.17 2.17 2.17]


In [16]:
# Задача № 13
# Дано координаты вектора в некотором базисе
# Выход: косинусы углов между этим вектором и осями координат ox, oy, oz

a = np.array([-1, 3, 2])

# ваш код

norm = np.linalg.norm(a) 
print(round(a[0]/norm, 2), round(a[1]/norm, 2), round(a[2]/norm, 2))

-0.27 0.8 0.53


In [19]:
# Задача № 14
# Дано модуль вектора, лежащего на плоскости и угол в радианах между осью ох и вектором
# Выход: проекции вектора на оси ох и оу

m = 2.3
angle_rad = 1.57

# ваш код

print(round(np.cos(angle_rad)*m, 2), round(np.sin(angle_rad)*m, 2))

0.0 2.3


In [ ]:
# Задача № 15
# Дано координаты векторов a и b
# Выход: модуль вектора a, модуль вектора c1 = (a+b), модуль вектора (с4+с3), 
# где вектор c3 в два раза длиннее вектора a и противоположен ему,
# вектор c4 - направлен в том же направлении, что и вектор b, но вдвое короче.
# Также вывести направляющие косинусы вектора b и направляющие косинусы вектора с2 = (a-b)

a = np.array([3, -2, 6])
b = np.array([-2, 1, 0])

# ваш код

c1 = a + b
c2 = a - b
c3 = -2 * a
c4 = b / 2

print(*(round(np.linalg.norm(v), 2) for v in (a, c1, c3 + c4)))
print(*(np.round(v / np.linalg.norm(v), 2) for v in (b, c2)))

7.0 6.16 14.6
[-0.89  0.45  0.  ] [ 0.6  -0.36  0.72]


In [22]:
# Задача № 16
# Дано координаты векторов a и b
# Выход: скалярное произведение векторов a и b

a = np.array([1, 1, 1])
b = np.array([1, 1, 1])

# ваш код

print(a.dot(b))

3


In [23]:
# Задача № 17
# Дано координаты векторов a и b
# Выход: косинус угла между этими векторами

a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

# ваш код

print(round(a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b)), 3))

0.0


In [24]:
# Задача № 18
# Дано координаты векторов a и b
# Выход: вычислить проекцию вектора a на вектор b

a = np.array([1, 1])
b = np.array([1, 0])

# ваш код

print(round(a.dot(b)/np.linalg.norm(b), 2))

1.0


In [26]:
# Задача № 19
# Дано координаты векторов a и b в ортонормированном базисе
# Выход: координаты векторного произведения векторов a и b

a = np.array([1, 0, 0])
b = np.array([0, 0, 1])

# ваш код

print(np.cross(a, b))

[ 0 -1  0]


In [27]:
# Задача № 20
# Дано координаты векторов a и b в ортонормированном базисе
# Выход: вычислить модуль векторного произведения

a = np.array([1, 0, 0])
b = np.array([0, 0, 1])

# ваш код

print(np.linalg.norm(np.cross(a, b)))

1.0


In [29]:
# Задача № 21
# Дано координаты векторов a и b в ортонормированном базисе
# Выход: вычислить синус угла между векторами

a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

# ваш код

sin_a = np.linalg.norm(np.cross(a, b)) / (np.linalg.norm(a) * np.linalg.norm(b))
print(sin_a)

1.0


In [30]:
# Задача № 22
# Дано координаты векторов a и b в ортонормированном базисе
# Выход: True, если вектора коллинеарны, False в противном случае

a = np.array([1, 0, 0])
b = np.array([-3, 0, 0])

# ваш код

print(np.cross(a, b).mean() == 0)

True


In [31]:
# Задача № 22
# Дано координаты векторов a, b, c
# Выход: вычислить скалярное произведение a и векторного произведения b, c

a = np.array([1, 2, 0])
b = np.array([2, 1, 3])
c = np.array([0, 2, 1])

# ваш код

print(a.dot(np.cross(b, c)))

-9


In [32]:
# Задача № 23
# Дано координаты векторов a, b, c
# Выход: вычислить векторное произведение a и векторного произведения b, c

a = np.array([3, 2, 1])
b = np.array([-1, 2, 0])
c = np.array([0, 2, 3])

# ваш код

result = np.cross(a, np.cross(b, c))
print(result)

[-7 12 -3]


In [33]:
# Задача № 24
# Дано координаты векторов a, b, c
# Выход: вычислить модуль векторного произведения a и векторного произведения b, c

a = np.array([-1, 0, 0])
b = np.array([0, 1, 0])
c = np.array([0, 0, -2])

# ваш код

result = np.linalg.norm(np.cross(a, np.cross(b, c)))
print(result)

0.0


In [34]:
# Задача № 25
# Дано координаты векторов a, b, c
# Выход: True если векторы образуют ортогональный базис, иначе - False

a = np.array([1, 0, 0])
b = np.array([0, -1, 0])
c = np.array([0, 0, 3])

# ваш код

result = np.cross(a, np.cross(b, c))
print(result.mean()==0)

True


In [35]:
# Задача № 26
# Дано координаты векторов a, b, c
# Выход: True если векторы компланарны, иначе - False

a = np.array([1, 1, 0])
b = np.array([1, 1, 1])
c = np.array([1, -1, 1])

# ваш код

result = np.dot(a, np.cross(b, c))
print(result==0)

False


In [44]:
# Задача № 27
# Дано координаты точек A, B, вектора a
# Выход: 1. Координаты вектора AB, который указывает направление от точки A до точки B
#        2. модуль вектора AB
#        3. Направляющие косинусы вектора AB, показывающие отношение проекций вектора AB на координатные оси к его длине
#        4. Координаты точки C, с которой совпадает конец вектора a, если его начало совпадает с точкой B

A = np.array([1, -2, 0])
B = np.array([-2, 3, -1])
a = np.array([0, 1, 2])

# ваш код

AB = B-A
nAB = np.linalg.norm(AB)
cos_ab = AB/nAB
C = a+B
print(AB)
print(nAB)
print(cos_ab)
print(C)


[-3  5 -1]
5.916079783099616
[-0.50709255  0.84515425 -0.16903085]
[-2  4  1]


In [46]:
# Задача № 28
# Дано модуль вектора a, углы в градусах, которые этот вектор составляет с осями x, y, z
# Выход: проекции вектора a на соответствующие оси

mod_a = 3
angle_x = 45
angle_y = 60
angle_z = 120

# ваш код

result_1 = mod_a*np.cos(np.deg2rad(angle_x)) 
result_2 = mod_a*np.cos(np.deg2rad(angle_y))
result_3 = mod_a*np.cos(np.deg2rad(angle_z))
print(result_1, result_2, result_3)

2.121320343559643 1.5000000000000004 -1.4999999999999993
